### ISSUE TITLE
大佬！能不能给$$R客户端添加$$RR的混淆

### ISSUE THREAD

**Issue by CODEXP777** [hanwckf/rt-n56u#10]
您支持的是原版的$$R混淆协议，能不能把akkariiin（https://github.com/shadowsocksrr/shadowsocksr/commits/akkariiin/master ）
的混淆

auth_chain_c | auth_chain_d | auth_chain_e | auth_chain_f ，添加进去呢！谢谢！

**Comment by hanwckf** [comment]
我个人认为ssrr这几个所谓的协议纯粹是瞎折腾，所以不打算更新……

**Comment by ntgeralt** [comment]
经过今年6/4 ss ssr大面积封ip，亲测儿童节上午chain a 3个国家节点都被禁ip，已经不打算再用ss系……
