### ISSUE TITLE
XY-C1的网络信息里那个2.4G页没有删除。

### ISSUE THREAD

**Issue by MayaGates** [hanwckf/rt-n56u#100]
XY-C1的网络信息里那个2.4G无线的tab页没有删除。

	if(!support_2g_radio()){
		menuL2_link[1] = "";  //remove 2G
		menuL2_title[1] = "";
		tabtitle[0].splice(1,6);
		tablink[0].splice(1,6);
+		tabtitle[8].splice(1,1);
+		tablink[8].splice(1,1);
}
但是如果这样加两行的话，那个nvram_dump("wlan11b_2g.log","")还会倒进去第一个WAN的tab里，怎么办？

**Comment by Yonsm** [comment]
为完美主义点赞。但不建议删除，如你所说的一样，不好操作，我之前也试过；就当留着看一眼确认 WIFI 确定是 disabled 的，心里就舒坦多了。

**Comment by MayaGates** [comment]
操作模式里那个AP也可以干掉。

**Comment by MayaGates** [comment]
虽有SATA设置图标但是无法识别硬盘，加了下面这几句就可以识别了。
CONFIG_SATA_PMP=y
CONFIG_MTK_XHCI=y
CONFIG_RT3XXX_EHCI_OHCI=y

**Comment by Yonsm** [comment]
> 虽有SATA设置图标但是无法识别硬盘，加了下面这几句就可以识别了。
> CONFIG_SATA_PMP=y
> CONFIG_MTK_XHCI=y
> CONFIG_RT3XXX_EHCI_OHCI=y
已集成到 https://github.com/Yonsm/Padavan，到我那边去讨论这个吧，大家确认好了我会PR到hanwckf这里来
