### ISSUE TITLE
希望能加入更多dns相关工具

### ISSUE THREAD

**Issue by kailinda** [hanwckf/rt-n56u#107]
最近，dns这方面是自己搭建的，但是效果并不很好，速度慢，缓存低，不智能。
希望，能加入pdnsd和chinadns，还有dnsutil（dig）等工具，方便选择和调试。
希望，能加入dns over https/tls 等高级工具。
当然，大神有更好解决方案，最好。
感谢大神辛苦更新~

**Comment by hcym** [comment]
现在的环境根本没用，直接隧道出去，隧道通畅就没问题，没有隧道你用什么dnsdnx都出不去

**Comment by hanwckf** [comment]
pdnsd这种方案早就被dns-forwarder代替了，Chinadns存在无法解决的bug并且没人维护所以不会再加进来

**Comment by kailinda** [comment]
> 
> 
> 现在的环境根本没用，直接隧道出去，隧道通畅就没问题，没有隧道你用什么dnsdnx都出不去

好吧，其实我发现隧道出去，也有污染，貌似隧道出去的dm530.com都是污染的。很奇葩。

**Comment by kailinda** [comment]
> 
> 
> pdnsd这种方案早就被dns-forwarder代替了，Chinadns存在无法解决的bug并且没人维护所以不会再加进来

好的，https这个呢。不过，目前够用。
