### ISSUE TITLE
WR1200JS无线信号过山车    请排查

### ISSUE THREAD

**Issue by jhcn** [hanwckf/rt-n56u#11]
![9ogk39 am7n kdxj e99z7w](https://user-images.githubusercontent.com/31360460/48847638-06a78f80-eddd-11e8-949b-9e6cafaad763.png)

**Comment by hanwckf** [comment]
2.4g还是5g？请尝试其他Padavan固件

**Comment by jhcn** [comment]
> 2.4g还是5g？请尝试其他Padavan固件

5G     2.4g未测试     10月31号左右编译出来的固件没有这个问题
