### ISSUE TITLE
【安全问题】此代码屏蔽后，其中一个终端登录管理页面后，其他终端无需密码登录管理页面

### ISSUE THREAD

**Issue by hiboyhiboy** [hanwckf/rt-n56u#12]
https://github.com/hanwckf/rt-n56u/blob/8307faa8604dda41c4fd801fa21663a890081299/trunk/user/httpd/httpd.c#L953

【安全问题】此代码屏蔽后，其中一个终端登录管理页面后，其他终端无需密码登录管理页面

**Comment by hanwckf** [comment]
当时觉得超时时间太长，在别的终端要等很久才能登进去，现在把timeout改成30s了...
