### ISSUE TITLE
K2P_nano日志请教

### ISSUE THREAD

**Issue by kingyan** [hanwckf/rt-n56u#121]
日志中出现如下日志，请问是什么问题，怎么才能关闭掉这些日志呢。
用的您提供的刷机文件，用的4版的驱动。

Oct  1 19:24:20 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000004
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0x00000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c064=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c068=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c06C=0x00000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060244=0x00000200
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060248=0x00000010
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060258=0x00000020
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206025C=0x003D04D7
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000C941
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct  1 19:24:20 kernel: ====Bnad0 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 24730
Oct  1 19:24:20 kernel: OBSS Air Time = 41052
Oct  1 19:24:20 kernel: My Tx Air Time = 22928
Oct  1 19:24:20 kernel: My Rx Air Time = 0
Oct  1 19:24:20 kernel: EDCCA Time = 0
Oct  1 19:24:20 kernel: PD count = 8052d
Oct  1 19:24:20 kernel: MDRDY Count = f
Oct  1 19:24:20 kernel: ====Bnad1 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 37186
Oct  1 19:24:20 kernel: OBSS Air Time = 0
Oct  1 19:24:20 kernel: My Tx Air Time = 811244
Oct  1 19:24:20 kernel: My Rx Air Time = 79837
Oct  1 19:24:20 kernel: EDCCA Time = 24513
Oct  1 19:24:20 kernel: PD count = 68e0000
Oct  1 19:24:20 kernel: MDRDY Count = 68c0000
Oct  1 19:24:20 kernel: Ser                       ,::E  R  , stat=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000008
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0xC0000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000D1B2
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct  1 19:24:20 kernel: ====Bnad0 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 24730
Oct  1 19:24:20 kernel: OBSS Air Time = 41052
Oct  1 19:24:20 kernel: My Tx Air Time = 22928
Oct  1 19:24:20 kernel: My Rx Air Time = 0
Oct  1 19:24:20 kernel: EDCCA Time = 0
Oct  1 19:24:20 kernel: PD count = 8052d
Oct  1 19:24:20 kernel: MDRDY Count = f
Oct  1 19:24:20 kernel: ====Bnad1 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 37186
Oct  1 19:24:20 kernel: OBSS Air Time = 0
Oct  1 19:24:20 kernel: My Tx Air Time = 811244
Oct  1 19:24:20 kernel: My Rx Air Time = 79837
Oct  1 19:24:20 kernel: EDCCA Time = 24513
Oct  1 19:24:20 kernel: PD count = 68e0000
Oct  1 19:24:20 kernel: MDRDY Count = 68c0000
Oct  1 19:24:20 kernel: Ser                       ,::E  R  , stat=0x00000001
Oct  1 19:24:20 kernel: cut_through_token_list_destroy(): 8748aa88,8748aa88
Oct  1 19:24:20 kernel: cut_through_token_list_destroy(): 8748aa98,8748aa98
Oct  1 19:24:20 kernel: Use dev_alloc_skb
Oct  1 19:24:20 kernel: cut_through_token_list_init(): TokenList inited done!id_head/tail=0/4096
Oct  1 19:24:20 kernel: cut_through_token_list_init(): 8748aa88,8748aa88
Oct  1 19:24:20 kernel: cut_through_token_list_init(): TokenList inited done!id_head/tail=0/4096
Oct  1 19:24:20 kernel: cut_through_token_list_init(): 8748aa98,8748aa98
Oct  1 19:24:20 kernel: RX[0] DESC a77cc000 size = 16384
Oct  1 19:24:20 kernel: RX[1] DESC a77ca000 size = 8192
Oct  1 19:24:20 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000010
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0xF0000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000EE65
Oct  1 19:24:20 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct  1 19:24:20 kernel: ====Bnad0 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 24730
Oct  1 19:24:20 kernel: OBSS Air Time = 41052
Oct  1 19:24:20 kernel: My Tx Air Time = 22928
Oct  1 19:24:20 kernel: My Rx Air Time = 0
Oct  1 19:24:20 kernel: EDCCA Time = 0
Oct  1 19:24:20 kernel: PD count = 8052d
Oct  1 19:24:20 kernel: MDRDY Count = f
Oct  1 19:24:20 kernel: ====Bnad1 Enable = 1====
Oct  1 19:24:20 kernel: Channel Busy Time = 37186
Oct  1 19:24:20 kernel: OBSS Air Time = 0
Oct  1 19:24:20 kernel: My Tx Air Time = 811244
Oct  1 19:24:20 kernel: My Rx Air Time = 79837
Oct  1 19:24:20 kernel: EDCCA Time = 24513
Oct  1 19:24:20 kernel: PD count = 68e0000
Oct  1 19:24:20 kernel: MDRDY Count = 68c0000

**Comment by hanwckf** [comment]
可以换5.0驱动试一试。如果不是经常出现这种错误的话无需理会。
