### ISSUE TITLE
RT-AC1200GU编译bug

### ISSUE THREAD

**Issue by llouislu** [hanwckf/rt-n56u#122]
执行到这一步的时候，出现以下错误
```
$ sudo ./build_firmware_modify RT-AC1200GU
Target uClibc config (/opt/rt-n56u/trunk/configs/boards/RT-AC1200GU/libc.config) not found! Terminate.
```
大概原因是在trunk/configs/boards/RT-AC1200GU下没有libc.config

手动ln -s后正常编译，固件未测试是否正常

另外，这个型号能否加single sku profile?

**Comment by hanwckf** [comment]
这个型号是别的网友pr过来的，我自己没有这款机器所以也没测试过。Single sku可以从别的同无线芯片的机器目录里复制过来，然后要在kernel config里打开这个选项。
