### ISSUE TITLE
希望适配DIR-878

### ISSUE THREAD

**Issue by iayee** [hanwckf/rt-n56u#131]
DIR-878比DIR-882少了两个USB口，现在用的882的固件，能否把两个USB图标和USB应用栏去掉，强迫症看着很难受，感谢~

**Comment by cuikangyi** [comment]
既然都todo了，那我就不客气了，再来一个摩托罗拉mr2600的可好，这货就是882，gpio和882都一样，只是硬件少了个usb2.0

**Comment by cuikangyi** [comment]
算了，我把之前我fork的添加mr2600的直接pr吧

**Comment by Young-3** [comment]
同878，能否添加ssr订阅，现在ssr只有一个节点，谢谢h大
