### ISSUE TITLE
关于界面的建议

### ISSUE THREAD

**Issue by Lamyks** [hanwckf/rt-n56u#132]
1.建议将www/Makefile中
LABEL_COPYRIGHT_TEXT="© 2011-2019 Padavan \& N56U project community \& by hanwckf"
换成
LABEL_COPYRIGHT_TEXT="© 2011-2019 \<a href=\"https:\/\/bitbucket.org\/padavan\/rt-n56u\" target=\"blank\">Padavan\<\/a\> \& N56U project community \& by \<a href=\"https:\/\/github.com\/hanwckf\/rt-n56u\" target=\"blank\">hanwckf\<\/a\>"
如此在任何页面都可直接点击跳转项目页面

2.建议将CN.dict中词条 statusTitle_Sysytem=ZVMODELVZ 换成 statusTitle_Sysytem=无线网络状态，该页面实际显示的为 2.4/5GHz 的网络状态概览，“无线网络状态”显然更贴切，而非路由型号；如此网络地图界面则依次为：外部/内部网络状态、无线网络状态、设备状态

3.建议将关机按钮的JS提示语
JS_shutdown=关机后需要手动断电接电才能启动路由！！！
修改为
JS_shutdown=关机后需要手动断电并重新接电才能启动路由！！！
这样从语言表述上合理些，不会那么拗口

**Comment by Os-glthub** [comment]
-网络状态图标显示红叉，也无速率显示。希望修复。
