### ISSUE TITLE
求加入v2ray

### ISSUE THREAD

**Issue by w64139303** [hanwckf/rt-n56u#135]
万人血书求加入啊

**Comment by godsped** [comment]
me too

**Comment by chaohua27** [comment]
不知道是H大忘记了还是确实有困难，我发的请求被标记为TODO到现在几个月了。不过还是感谢H大的付出。

**Comment by lunafe** [comment]
最主要的困难可能在于由Golang编写的V2ray只是最主要的Binary就接近15MB，要是包含GeoIP和GeoSite就更大了。对于很多路由器要装下这么大的文件的文件是很困难的。另外，目前V2ray还无法稳定在128MB RAM的小内存设备上运行。

**Comment by w64139303** [comment]
可以使用upx压缩，这里有方法 https://github.com/felix-fly/v2ray-padavan

**Comment by ntgeralt** [comment]
@lunafe v2ray core 3.4mb，K2 ws tls 模式稳定运行 https://github.com/ntgeralt/v2ray-for-padavan
