### ISSUE TITLE
日志报一堆东西，请大神看看~

### ISSUE THREAD

**Issue by kailinda** [hanwckf/rt-n56u#137]
Oct 15 12:56:17 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000004
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c064=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c068=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206c06C=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060244=0x00000200
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060248=0x00000010
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x82060258=0x00000020
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x8206025C=0x004305B4
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000A4EF
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct 15 12:56:17 kernel: ====Bnad0 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 91109
Oct 15 12:56:17 kernel: OBSS Air Time = 16596
Oct 15 12:56:17 kernel: My Tx Air Time = 824060
Oct 15 12:56:17 kernel: My Rx Air Time = 107276
Oct 15 12:56:17 kernel: EDCCA Time = 3497
Oct 15 12:56:17 kernel: PD count = 4b6015a
Oct 15 12:56:17 kernel: MDRDY Count = 46d0007
Oct 15 12:56:17 kernel: ====Bnad1 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 4084
Oct 15 12:56:17 kernel: OBSS Air Time = 0
Oct 15 12:56:17 kernel: My Tx Air Time = 0
Oct 15 12:56:17 kernel: My Rx Air Time = 0
Oct 15 12:56:17 kernel: EDCCA Time = 0
Oct 15 12:56:17 kernel: PD count = 3e0000
Oct 15 12:56:17 kernel: MDRDY Count = a0000
Oct 15 12:56:17 kernel: Ser                       ,::E  R  , stat=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000008
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0xC0000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000A4F3
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct 15 12:56:17 kernel: ====Bnad0 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 91109
Oct 15 12:56:17 kernel: OBSS Air Time = 16596
Oct 15 12:56:17 kernel: My Tx Air Time = 824060
Oct 15 12:56:17 kernel: My Rx Air Time = 107276
Oct 15 12:56:17 kernel: EDCCA Time = 3497
Oct 15 12:56:17 kernel: PD count = 4b6015a
Oct 15 12:56:17 kernel: MDRDY Count = 46d0007
Oct 15 12:56:17 kernel: ====Bnad1 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 4084
Oct 15 12:56:17 kernel: OBSS Air Time = 0
Oct 15 12:56:17 kernel: My Tx Air Time = 0
Oct 15 12:56:17 kernel: My Rx Air Time = 0
Oct 15 12:56:17 kernel: EDCCA Time = 0
Oct 15 12:56:17 kernel: PD count = 3e0000
Oct 15 12:56:17 kernel: MDRDY Count = a0000
Oct 15 12:56:17 kernel: Ser                       ,::E  R  , stat=0x00000001
Oct 15 12:56:17 kernel: cut_through_token_list_destroy(): 87483a08,87483a08
Oct 15 12:56:17 kernel: cut_through_token_list_destroy(): 87483a18,87483a18
Oct 15 12:56:17 kernel: Use dev_alloc_skb
Oct 15 12:56:17 kernel: cut_through_token_list_init(): TokenList inited done!id_head/tail=0/4096
Oct 15 12:56:17 kernel: cut_through_token_list_init(): 87483a08,87483a08
Oct 15 12:56:17 kernel: cut_through_token_list_init(): TokenList inited done!id_head/tail=0/4096
Oct 15 12:56:17 kernel: cut_through_token_list_init(): 87483a18,87483a18
Oct 15 12:56:17 kernel: RX[0] DESC a77c8000 size = 16384
Oct 15 12:56:17 kernel: RX[1] DESC a77c6000 size = 8192
Oct 15 12:56:17 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000010
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0xF0000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000A4F8
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct 15 12:56:17 kernel: ====Bnad0 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 91109
Oct 15 12:56:17 kernel: OBSS Air Time = 16596
Oct 15 12:56:17 kernel: My Tx Air Time = 824060
Oct 15 12:56:17 kernel: My Rx Air Time = 107276
Oct 15 12:56:17 kernel: EDCCA Time = 3497
Oct 15 12:56:17 kernel: PD count = 4b6015a
Oct 15 12:56:17 kernel: MDRDY Count = 46d0007
Oct 15 12:56:17 kernel: ====Bnad1 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 4084
Oct 15 12:56:17 kernel: OBSS Air Time = 0
Oct 15 12:56:17 kernel: My Tx Air Time = 0
Oct 15 12:56:17 kernel: My Rx Air Time = 0
Oct 15 12:56:17 kernel: EDCCA Time = 0
Oct 15 12:56:17 kernel: PD count = 3e0000
Oct 15 12:56:17 kernel: MDRDY Count = a0000
Oct 15 12:56:17 kernel: Ser                       ,::E  R  , stat=0x00000002
Oct 15 12:56:17 kernel: RTMPHandleInterrupt,::E  R  , status=0x00000020
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, MCU_COM_REG1=0xFC000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e4=0x00000001
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820681e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682e8=0x00000000
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820682ec=0x0000A4FE
Oct 15 12:56:17 kernel: RTMPHandleInterruptSerDump,::E  R	, 0x820f20fc=0x0C400008
Oct 15 12:56:17 kernel: ====Bnad0 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 122618
Oct 15 12:56:17 kernel: OBSS Air Time = 28006
Oct 15 12:56:17 kernel: My Tx Air Time = 407335
Oct 15 12:56:17 kernel: My Rx Air Time = 118121
Oct 15 12:56:17 kernel: EDCCA Time = 2494
Oct 15 12:56:17 kernel: PD count = 2ac015d
Oct 15 12:56:17 kernel: MDRDY Count = 2610006
Oct 15 12:56:17 kernel: ====Bnad1 Enable = 1====
Oct 15 12:56:17 kernel: Channel Busy Time = 7943
Oct 15 12:56:17 kernel: OBSS Air Time = 0
Oct 15 12:56:17 kernel: My Tx Air Time = 0
Oct 15 12:56:17 kernel: My Rx Air Time = 0
Oct 15 12:56:17 kernel: EDCCA Time = 0
Oct 15 12:56:17 kernel: PD count = 310000
Oct 15 12:56:17 kernel: MDRDY Count = 80000
Oct 15 12:56:17 kernel: Ser                       ,::E  R  , stat=0x00000003
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[0](us)=459711243
Oct 15 12:56:17 kernel: ExtEventBeaconLostHandler::FW LOG, Beacon lost ([k2p's mac addr]), Reason 0x11
Oct 15 12:56:17 kernel:   Beacon lost - SER happened!!!
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[1](us)=459853781
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[2](us)=459858500
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[3](us)=459933788
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[4](us)=460021692
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[5](us)=460021692
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[6](us)=460110504
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Time[7](us)=460110612
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T1 - T0(us)=142538
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T2 - T1(us)=4719
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T3 - T2(us)=75288
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T4 - T3(us)=87904
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T5 - T4(us)=0
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T6 - T5(us)=88812
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , T7 - T6(us)=108
Oct 15 12:56:17 kernel: SerTimeLogDump,::E  R  , Total Time(us)=399369

**Comment by kailinda** [comment]
kernel这方面 一直有报东西，希望大神有空处理下，毕竟稳定才是第一位的。感谢大神的辛苦付出~

**Comment by aklimzzh** [comment]
DIR882
我也有这个问题，看一下你2.4G还活着吗，我的扫不到了，感觉2.4G挂了
另外log里有个MAC地址，我是从MAC推断出是2.4G的

**Comment by aklimzzh** [comment]
@hanwckf 请大佬抽空帮忙看看这个issue，谢谢大佬

**Comment by hanwckf** [comment]
> @hanwckf 请大佬抽空帮忙看看这个issue，谢谢大佬

这个2.4g的error我也遇到过，不过不是经常出现，你这是经常出现？

**Comment by aklimzzh** [comment]
> > @hanwckf 请大佬抽空帮忙看看这个issue，谢谢大佬
> 
> 这个2.4g的error我也遇到过，不过不是经常出现，你这是经常出现？

只要打开2.4g就是这些log，而且2.4g的ssid无法搜索到。

**Comment by hanwckf** [comment]
> > > @hanwckf 请大佬抽空帮忙看看这个issue，谢谢大佬
> > 
> > 
> > 这个2.4g的error我也遇到过，不过不是经常出现，你这是经常出现？
> 
> 只要打开2.4g就是这些log，而且2.4g的ssid无法搜索到。

我是问开issue的那个朋友.....你这台机器估计是硬件损坏了，建议设法刷回原厂固件然后换货。

**Comment by kailinda** [comment]
开机以后貌似只出现了一次。

最近又看到了这个：
Oct 28 22:41:32 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 01:52:18 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 01:52:35 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 01:52:59 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 01:53:22 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 01:54:31 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 02:04:13 kernel: MacTableInsertEntry, Entry Idx:2 is inuse, overlap
Oct 29 14:09:22 NTP Client: Synchronizing time to cn.pool.ntp.org.
Oct 29 14:09:23 NTP Client: System time changed, offset: 0.048252s
Oct 29 19:11:38 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!
Oct 29 19:11:43 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!
Oct 29 19:11:49 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!

**Comment by hanwckf** [comment]
不是经常出现的话无需理会，我这也时不时有报错，不影响正常使用。

**Comment by kailinda** [comment]
好的 支持大神~
