### ISSUE TITLE
请更新部分软件源中过时的guess文件

### ISSUE THREAD

**Issue by SuzukiHonoka** [hanwckf/rt-n56u#148]
过时的guess无法识别某些架构，
无论是否处理，都请给一个答复，
谢谢。

**Comment by hanwckf** [comment]
https://github.com/hanwckf/rt-n56u/commit/c72b71f4214682baa01560d5c6988925f22ddd19
https://github.com/hanwckf/rt-n56u/commit/8f8d4946cda5ba22ff1528f8ccf768ff227a7799
