### ISSUE TITLE
It is possible to adpat for Asusu RT-N56U rev1?

### ISSUE THREAD

**Issue by Plushkin** [hanwckf/rt-n56u#149]
I try to compile for rt-n56u rev 1, but it wasn't start( please help

**Comment by hanwckf** [comment]
Unsupported old devices have been moved to `trunk/configs/boards/.unsupported/` and `trunk/configs/templates/.unsupported/`, you can recover these config files to original folder. But the kernel config file need to re-generate ( copy `kernel-3.4.x.config` to `trunk/linux-3.4.x/.config` and run `make menuconfig` ). You may need to adjust template config file too.
