### ISSUE TITLE
DIR-882 连接160Mhz AC9560网卡速度不正常

### ISSUE THREAD

**Issue by rancent2017** [hanwckf/rt-n56u#152]
1. 5G开启160Mhz，网卡连接速率显示1.7Gbps.
2. 路由器与网卡距离不到1M，最高iperf3测速度大概510Mbps.
3. WAN设置开启了硬件NAT，测试速率480-490Mbps
4. 硬件NAT和 SFE 同时开启速率 500-510Mbps
5. 5G信道36，其余设置未动

**Comment by MeIsReallyBa** [comment]
你先确定有线下iperf3能不能跑起来。

**Comment by rancent2017** [comment]
@MeIsReallyBa 有线可以。Wan to Lan  iperf3 950M，Lan to Lan 960M , Lan/Wan 有线都可以跑满

**Comment by MeIsReallyBa** [comment]
iperf3开了多线程吗。。。。单线程无线下有点容易跑不起来

**Comment by MeIsReallyBa** [comment]
我手上没9560，但ax200和8265速度都是正常的

**Comment by rancent2017** [comment]
@MeIsReallyBa iperf3测不到后拿http拉文件测过，很奇怪，编译了新版刷上去还低了点...  另外我这里还有878改了个无USB的配置编译刷上也很奇怪... 速度866Mbps都不到..

**Comment by ivanlee93** [comment]
> @MeIsReallyBa iperf3测不到后拿http拉文件测过，很奇怪，编译了新版刷上去还低了点... 另外我这里还有878改了个无USB的配置编译刷上也很奇怪... 速度866Mbps都不到..

你好，无USB的配置可以分享一下吗？我也是878

**Comment by rancent2017** [comment]
@ivanlee93 https://github.com/rancent2017/DIR-878 根据882修改来的

**Comment by ivanlee93** [comment]
> @ivanlee93 https://github.com/rancent2017/DIR-878 根据882修改来的

谢谢

**Comment by rancent2017** [comment]
@ivanlee93 hamwckf已经添加了新的878，git同步下吧，我的还有些问题就先取消了
