### ISSUE TITLE
Newifi3 2.4G上网速度很慢

### ISSUE THREAD

**Issue by ddvcx** [hanwckf/rt-n56u#154]
连接2.4G上网的时候，比如打开淘宝，要5 6秒才会刷出来，像卡住了
就算站在路由器边上也是一样
连接5G的时候速度很快，一下就打开
有线也是很快

**Comment by hanwckf** [comment]
这个mt7603的驱动可能还是存在许多问题，我现在手头没有7603的机器，也没法尝试更换新版本驱动测试

**Comment by xnxy2012** [comment]
lede里面有最新的驱动，大神能否移至过来？

**Comment by hanwckf** [comment]
不是mt76开源驱动，我说的是私有驱动

**Comment by Comah** [comment]
2.4的确很慢 不知为何 。5g却快得不行

**Comment by lunafe** [comment]
网上搜了一下，Newifi3 2.4g问题似乎是通病，可以试试刷eeprom。

参考：
https://www.right.com.cn/forum/thread-551141-1-1.html
https://aisoa.cn/post-2465.html
https://aisoa.cn/post-2281.html

**Comment by ddvcx** [comment]
> 网上搜了一下，Newifi3 2.4g问题似乎是通病，可以试试刷eeprom。
> 
> 参考：
> https://www.right.com.cn/forum/thread-551141-1-1.html
> https://aisoa.cn/post-2465.html
> https://aisoa.cn/post-2281.html

不是发射功率问题啊，我站在路由器边上，2.4G信号满格的情况下，打开网站还是很慢

**Comment by Comah** [comment]
> > 网上搜了一下，Newifi3 2.4g问题似乎是通病，可以试试刷eeprom。
> > 参考：
> > https://www.right.com.cn/forum/thread-551141-1-1.html
> > https://aisoa.cn/post-2465.html
> > https://aisoa.cn/post-2281.html
> 
> 不是发射功率问题啊，我站在路由器边上，2.4G信号满格的情况下，打开网站还是很慢

好的谢谢

**Comment by ntgeralt** [comment]
但我用新3 2.4G测试似乎很正常没感受到问题。直视10米 5MB/S，转角关门维持2MB/S
@hanwckf  另外你新增的关机按钮，自从更新后误按了三次+……
建议放其他地方，如【注销】的左侧

**Comment by lunafe** [comment]
> 
> 
> > 网上搜了一下，Newifi3 2.4g问题似乎是通病，可以试试刷eeprom。
> > 参考：
> > https://www.right.com.cn/forum/thread-551141-1-1.html
> > https://aisoa.cn/post-2465.html
> > https://aisoa.cn/post-2281.html
> 
> 不是发射功率问题啊，我站在路由器边上，2.4G信号满格的情况下，打开网站还是很慢

就目前我在网上能找到的信息，似乎是1.1版本的主板设计有问题，可能是主板内部存在干扰什么的导致的2.4g频率工作不稳定，网上所见的有关问题也大多是在信号良好的情况下传输速度很慢，而不是信号强度不够。而1.2的硬体版本并没有这个问题。

**Comment by yu13740000** [comment]
cpu和usb部分做屏蔽罩，效果明显。
无线部分屏蔽起反作用，所以最后拆了无线部分的屏蔽罩子。

**Comment by Comah** [comment]
> 但我用新3 2.4G测试似乎很正常没感受到问题。直视10米 5MB/S，转角关门维持2MB/S
> @hanwckf 另外你新增的关机按钮，自从更新后误按了三次+……
> 建议放其他地方，如【注销】的左侧

和我的一样 2.4放客厅 然后在放房间关门 1-2M/S 没办法突破的了

**Comment by ddvcx** [comment]
> 不是mt76开源驱动，我说的是私有驱动

pandorabox的驱动2.4G速度很快很稳定，可以把它移植过来吗
