### ISSUE TITLE
刷了10-19 k2p nano版本隔一段时间跑以下这个重复错误？

### ISSUE THREAD

**Issue by zydevn** [hanwckf/rt-n56u#159]
<img width="1006" alt="截屏2019-11-0216 48 46" src="https://user-images.githubusercontent.com/57285010/68068515-ad880000-fd90-11e9-80ec-27c8eb867e5d.png">

**Comment by zydevn** [comment]
求hanwckf大神帮忙看看

**Comment by Os-glthub** [comment]
<img width="598" alt="微信截图_20191113222647" src="https://user-images.githubusercontent.com/52124855/68772444-caf87c00-0664-11ea-9795-834a96826f85.png">
9.29号后的版本都出现这个红叉，PC和手机端都一样。换无灯的无此现象，不影响使用，强迫症希望能修复。实测固件K2P ，DIR

**Comment by hanwckf** [comment]
> 求hanwckf大神帮忙看看

检查过是无关紧要的日志，已经去除该输出
