### ISSUE TITLE
k2p这2个报错有影响吗？

### ISSUE THREAD

**Issue by PHCSJC** [hanwckf/rt-n56u#163]
K2P
固件版本：v2019-10-19
刷的固件：K2P_nano.trx

Nov  6 17:19:52 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!
Nov  6 17:19:53 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!
Nov  6 17:19:54 kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!
Nov  7 09:50:23 kernel: MacTableInsertEntry, Entry Idx:13 is inuse, overlap
Nov  7 09:50:50 kernel: MacTableInsertEntry, Entry Idx:13 is inuse, overlap
Nov  7 09:57:05 kernel: MacTableInsertEntry, Entry Idx:13 is inuse, overlap
Nov  7 09:57:29 kernel: MacTableInsertEntry, Entry Idx:13 is inuse, overlap

**Comment by hanwckf** [comment]
没有影响……
