### ISSUE TITLE
win10 linux子系统编译问题

### ISSUE THREAD

**Issue by kingyan** [hanwckf/rt-n56u#164]
试过了win10 linux子系统的ununtu 16和18版本，都一样的问题，卡住编译不下去。

使用这个命令编译 fakeroot ./build_firmware_modify PSG1218 卡在这里过不去。

gcc   mksquashfs.o read_fs.o action.o swap.o pseudo.o compressor.o sort.o progressbar.o read_file.o info.o restore.o process_fragments.o caches-queues-lists.o gzip_wrapper.o xz_wrapper.o xattr.o read_xattrs.o -lpthread -lm -lz /opt/rt-n56u/trunk/tools/mksquashfs_xz/xz-5.2.4/src/liblzma/.libs/liblzma.a -o mksquashfs
gcc   unsquashfs.o unsquash-1.o unsquash-2.o unsquash-3.o unsquash-4.o swap.o compressor.o unsquashfs_info.o gzip_wrapper.o xz_wrapper.o read_xattrs.o unsquashfs_xattr.o -lpthread -lm -lz /opt/rt-n56u/trunk/tools/mksquashfs_xz/xz-5.2.4/src/liblzma/.libs/liblzma.a -o unsquashfs
make[3]: Leaving directory '/opt/rt-n56u/trunk/tools/mksquashfs_xz/squashfs-4.3'
cp squashfs-4.3/unsquashfs ./
make[2]: Leaving directory '/opt/rt-n56u/trunk/tools/mksquashfs_xz'
make[1]: Leaving directory '/opt/rt-n56u/trunk/tools'
make ARCH=mips CROSS_COMPILE=/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc- -j2 -C linux-3.4.x  || exit 1
make[1]: Entering directory '/opt/rt-n56u/trunk/linux-3.4.x'
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h

如果使用这个命令 sudo  ./build_firmware_modify PSG1218 可以正常编译
使用sudo命令编译，接下来的编译日志如下

  CALL    scripts/checksyscalls.sh
make[1]: Leaving directory '/opt/rt-n56u/trunk/linux-3.4.x'
make ARCH=mips CROSS_COMPILE=/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/bin/mipsel-linux-uclibc- -C linux-3.4.x dep
make[1]: Entering directory '/opt/rt-n56u/trunk/linux-3.4.x'
make[1]: Nothing to be done for 'dep'.
make[1]: Leaving directory '/opt/rt-n56u/trunk/linux-3.4.x'

现在看，使用fakeroot应该是卡在 CALL    scripts/checksyscalls.sh 这里过不去。
并且win10 linux子系统用fakeroot编译的话会报如下错误
fakeroot, while creating message channels: 
Function not implemented This may be due to a lack of SYSV IPC support.
 fakeroot: error while starting the ``faked' daemon. kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec] 
使用如下方法解决：sudo update-alternatives --set fakeroot /usr/bin/fakeroot-tcp
使用fakeroot-tcp替换fakeroot
https://github.com/microsoft/WSL/issues/4067

但导致的结果就是编译卡住，只能使用sudo  ./build_firmware_modify PSG1218 编译，用fakeroot命令编译在win10 linux子系统下编译还是会卡住不动。

**Comment by hanwckf** [comment]
好，我修改一下说明

**Comment by kingyan** [comment]
新代码提示缺少 help2man 这个包
安装help2man：sudo apt install help2man
