### ISSUE TITLE
美元可能出现的流量死循环，导致cpu100%~

### ISSUE THREAD

**Issue by kailinda** [hanwckf/rt-n56u#165]
如果是域名，没有自动加入代理排除列表，直接死循环。如果是ip，貌似是正常的。
我之前刷的一个老版本有这个问题，看了更新内容，应该最新版也有类似问题。
请老大有空处理一下，感谢大神的辛苦付出~

**Comment by hanwckf** [comment]
目前脚本不支持域名服务器，没有相关的处理

**Comment by yu13740000** [comment]
域名可以用啊，也没cpu100%

**Comment by kailinda** [comment]
好吧~ 谢谢~

**Comment by ntgeralt** [comment]
域名也可以用。楼主问题估计和自身走透明代理有关，关了那个试试

**Comment by kailinda** [comment]
对的 开了自身代理 但是也不应该死循环 应该是原版美元的bug 只能自定义美元脚本解决了
