### ISSUE TITLE
构建固件时出现cpio: not found错误

### ISSUE THREAD

**Issue by 909128q8** [hanwckf/rt-n56u#172]
环境：MacOS安装docker，Ubuntu运行在docker里
# MacOSx @ MacOSXsMBP in ~/Documents/test [9:02:37]
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              775349758637        2 weeks ago         64.2MB

现象: build firmware 时出现

/opt/rt-n56u/trunk/tools/romfs-inst.sh /opt/rt-n56u/trunk/user/shadowsocks/scripts/ /usr/bin/
/opt/rt-n56u/trunk/tools/romfs-inst.sh: 69: /opt/rt-n56u/trunk/tools/romfs-inst.sh: cpio: not found
chmod: cannot access './ss-tunnel.sh': No such file or directory
chmod: cannot access './ss-watchcat.sh': No such file or directory
chmod: cannot access './update_gfwlist.sh': No such file or directory
chmod: cannot access './ss-rules': No such file or directory
chmod: cannot access './shadowsocks.sh': No such file or directory

原因：ubuntu里缺少cpio 这个package
解决方法：安装 cpio， 
                   apt install cpio
后续：在此环境下编译还需要安装module-init-tools和wget这两个包。

**Comment by hanwckf** [comment]
安装cpio
