### ISSUE TITLE
日志持续输出kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!

### ISSUE THREAD

**Issue by PigodChen** [hanwckf/rt-n56u#174]
日志持续输出kernel: APPeerProbeReqAction():shiang! PeerProbeReqSanity failed!

固件K2P-5.0驱动，输出日子的好像是2.4g无线，关掉就没有，打开就有日志

但是看起来不影响使用，
![批注 2019-11-19 100540](https://user-images.githubusercontent.com/25973637/69110099-947f8e80-0ab4-11ea-88a3-c703807701f5.jpg)

**Comment by hanwckf** [comment]
检查过是无关紧要的日志，已经去除该输出
