### ISSUE TITLE
什么时间可以适配MI-R3G？

### ISSUE THREAD

**Issue by myd2898129** [hanwckf/rt-n56u#177]
一直很喜欢大神的固件，不知什么时候可以适配R3G

**Comment by azgh** [comment]
同样期待

**Comment by MxCen** [comment]
同样期待。我自己按照http://prometheus.freize.net/中的R3G配置文件编译的固件无法启动。
[MI-R3G_configs.zip](https://github.com/hanwckf/rt-n56u/files/3910104/MI-R3G_configs.zip)

**Comment by ASUS-CPU** [comment]
同样期待

**Comment by hanwckf** [comment]
已经添加配置文件，不过手头没有机器测试，楼上几位自己编译可以试一下能不能用

**Comment by ASUS-CPU** [comment]
> 已经添加配置文件，不过手头没有机器测试，楼上几位自己编译可以试一下能不能用

我来测试 大大放出来  我测试

**Comment by hanwckf** [comment]
@ASUS-CPU @myd2898129 @azgh @MxCen 
[MI-R3G.zip](https://github.com/hanwckf/rt-n56u/files/3983850/MI-R3G.zip)

**Comment by ASUS-CPU** [comment]
> @ASUS-CPU @myd2898129 @azgh @MxCen
> [MI-R3G.zip](https://github.com/hanwckf/rt-n56u/files/3983850/MI-R3G.zip)

测试。ok 可以启动。大大汉化一下 可以发布啦

**Comment by ASUS-CPU** [comment]
> @ASUS-CPU @myd2898129 @azgh @MxCen
> [MI-R3G.zip](https://github.com/hanwckf/rt-n56u/files/3983850/MI-R3G.zip)

一切正常 真香。

**Comment by hanwckf** [comment]
> > @ASUS-CPU @myd2898129 @azgh @MxCen
> > [MI-R3G.zip](https://github.com/hanwckf/rt-n56u/files/3983850/MI-R3G.zip)
> 
> 测试。ok 可以启动。大大汉化一下 可以发布啦

双清恢复出厂，默认就是中文

**Comment by ASUS-CPU** [comment]
正常了  一切正常  刷之前要双清
