### ISSUE TITLE
Dir 882 能否固定2.4G 40mHz 频宽

### ISSUE THREAD

**Issue by nightscorpio** [hanwckf/rt-n56u#179]
2.4G只能选择20/40mHz 吗？如何才能固定40mhz 频宽？

**Comment by Os-glthub** [comment]
设备支持的话，会自动选择40mhz

**Comment by nightscorpio** [comment]
有没有方法可以强制40mhz？   这边有手机只能选20mhz。  （三相S10+， 苹果x）

**Comment by hanwckf** [comment]
安卓强制20Mhz，路由器不能设置
