### ISSUE TITLE
PPPOE拨号自动断线重连，没有关闭echo选项

### ISSUE THREAD

**Issue by a541619896** [hanwckf/rt-n56u#18]
ISP移动，PPPOE服务器不规范，经常不会发送echo信号，WAN口设置中已经打开 自适应链路控制协议 (LCP) 响应间隔 ，但是每12小时仍然断线一次，像hiboyhiboy和荒野无灯的固件在WAN口设置页有Echo关闭的选项，我尝试直接修改nvram，nvram set wan_ppp_lcp=0然后nvram commit 但是仍然会6小时掉线，不会根据nvram中的数据去关闭nvram.

**Comment by hanwckf** [comment]
nvram里面那个设置项是人为添加的，实际上是rc处理的……

**Comment by hanwckf** [comment]
fixed in 10777fd581735d7b61ec0ccad30e5352a8b7eb63
