### ISSUE TITLE
curl没有本地证书，下载https会出错

### ISSUE THREAD

**Issue by laimama** [hanwckf/rt-n56u#188]
昨天反馈了wget不能下载https的问题，使用curl发现也有错误（curl: (60) cert verify failed: badcert_not_trusted），最后发现是没有本地证书，按照：https://blog.csdn.net/lixuande19871015/article/details/88788699
进行处理后正常了，希望老大能内置证书。

**Comment by hanwckf** [comment]
使用`curl -k`，多百度
