### ISSUE TITLE
编译结果显示的尺寸和实际结果不相符，远程日志请加入失败后重新带标记再发送一次。

### ISSUE THREAD

**Issue by MayaGates** [hanwckf/rt-n56u#19]
1/编译结果显示的尺寸和实际结果不相符。
2/日志输出到日志服务器时，请加入输出失败后打上重发标记再发送一次。

**Comment by hanwckf** [comment]
mkimage给的大小是还没假u-boot header前的大小，实际大小当然比mkimage显示的大小大64字节；
第二个不会修复
