### ISSUE TITLE
Chnroute模式下speedtest测速默认显示节点国家地区

### ISSUE THREAD

**Issue by yu13740000** [hanwckf/rt-n56u#195]
Chnroute模式下speedtest测速默认显示节点国家地区，一慌，以为是全局模式，希望能修改一下。

**Comment by hanwckf** [comment]
> Chnroute模式下speedtest测速默认显示节点国家地区，一慌，以为是全局模式，希望能修改一下。

因为
speedtest本身ip在国外，所以默认走了ss，以后再考虑加个白名单什么的acl控制

**Comment by yu13740000** [comment]
好的，感谢h大
