### ISSUE TITLE
是否可以考虑适配一下JHR-AC860m

### ISSUE THREAD

**Issue by xseven007** [hanwckf/rt-n56u#20]
是否可以考虑适配一下JHR-AC860m这个机器呢，这个机器和K2P是同款芯片，只不过WIFI部分是两个MT7615芯片分别个2.4G和5G用。用K2P的固件总感觉有一个芯片没有启动。

**Comment by hanwckf** [comment]
如果双7615的机器刷了这里的K2P固件的话，会让第一块7615工作在DBDC模式，第二块应该不工作……我手头没有双7615的机器因此短期不会增加这类机器

**Comment by xseven007** [comment]
如果修改编译的配置文件，把第二个wireless也和第一个一样选择mt7615n，然后选择5g的话，能不能驱动呢？如果需要，我可以寄一个AC860m给您。

**Comment by hanwckf** [comment]
可以在K2P的内核配置的基础上修改启用第二块7615，看看能否正常启动和配置

**Comment by xseven007** [comment]
# 1st Wireless Interface
	#
	# CONFIG_RT_FIRST_IF_NONE is not set
	# CONFIG_RT_FIRST_IF_RT3090 is not set
	# CONFIG_RT_FIRST_IF_RT5392 is not set
	# CONFIG_RT_FIRST_IF_RT5592 is not set
	# CONFIG_RT_FIRST_IF_RT3593 is not set
	# CONFIG_RT_FIRST_IF_MT7610E is not set
	# CONFIG_RT_FIRST_IF_MT7602E is not set
	# CONFIG_RT_FIRST_IF_MT7612E is not set
	# CONFIG_RT_FIRST_IF_MT7603E is not set
	CONFIG_RT_FIRST_IF_MT7615E=y
	CONFIG_RT_FIRST_IF_RANGE_2GHZ=y
	# CONFIG_RT_FIRST_IF_RANGE_5GHZ is not set
	CONFIG_RT_FIRST_IF_EEPROM_FLASH=y
	CONFIG_RT_FIRST_IF_RF_OFFSET=0x40000
	CONFIG_RT_FIRST_CARD=7615
	CONFIG_RT_FIRST_CARD_EEPROM="flash"
	
	#
	# 2nd Wireless Interface
	#
	CONFIG_RT_SECOND_IF_NONE=y
	# CONFIG_RT_SECOND_IF_RT3352_INIC is not set
	# CONFIG_RT_SECOND_IF_RT3090 is not set
	# CONFIG_RT_SECOND_IF_RT5392 is not set
	# CONFIG_RT_SECOND_IF_RT5592 is not set
	# CONFIG_RT_SECOND_IF_RT3593 is not set
	# CONFIG_RT_SECOND_IF_MT7610E is not set
	# CONFIG_RT_SECOND_IF_MT7602E is not set
	# CONFIG_RT_SECOND_IF_MT7612E is not set
	# CONFIG_RT_SECOND_IF_MT7603E is not set
	# CONFIG_RT_SECOND_IF_MT7615E is not set
	CONFIG_RT_SECOND_CARD=0
是修改这个部分吗？

**Comment by xseven007** [comment]
看了一下规格，是3x3的，所以这里也要改吧
        #define BOARD_NUM_ANT_5G_TX	2
	#define BOARD_NUM_ANT_5G_RX	2
	#define BOARD_NUM_ANT_2G_TX	2
	#define BOARD_NUM_ANT_2G_RX	2

**Comment by xseven007** [comment]
另外问一下，硬件转发是打不开的么

**Comment by hanwckf** [comment]
> 看了一下规格，是3x3的，所以这里也要改吧
> #define BOARD_NUM_ANT_5G_TX	2
> #define BOARD_NUM_ANT_5G_RX	2
> #define BOARD_NUM_ANT_2G_TX	2
> #define BOARD_NUM_ANT_2G_RX	2

其实是4x4，不过这个你写了大于2的数值目前是不起作用的，还需要修改别的地方，hwnat那边我还没仔细研究，短时间内不支持

**Comment by xseven007** [comment]
@hanwckf 编译之后，发现2.4G没有问题，但是5G网络WiFi无法打开

**Comment by xseven007** [comment]
# 2nd Wireless Interface
#
# CONFIG_RT_SECOND_IF_NONE is not set
# CONFIG_RT_SECOND_IF_RT3352_INIC is not set
# CONFIG_RT_SECOND_IF_RT3090 is not set
# CONFIG_RT_SECOND_IF_RT5392 is not set
# CONFIG_RT_SECOND_IF_RT5592 is not set
# CONFIG_RT_SECOND_IF_RT3593 is not set
# CONFIG_RT_SECOND_IF_MT7610E is not set
# CONFIG_RT_SECOND_IF_MT7602E is not set
# CONFIG_RT_SECOND_IF_MT7612E is not set
# CONFIG_RT_SECOND_IF_MT7603E is not set
CONFIG_RT_SECOND_IF_MT7615E=y
# CONFIG_RT_SECOND_IF_RANGE_2GHZ is not set
CONFIG_RT_SECOND_IF_RANGE_5GHZ=y
CONFIG_RT_SECOND_IF_EEPROM_FLASH=y
# CONFIG_RT_SECOND_IF_EEPROM_EFUSE is not set
# CONFIG_RT_SECOND_IF_EEPROM_PROM is not set
CONFIG_RT_SECOND_IF_RF_OFFSET=0x48000
CONFIG_RT_SECOND_CARD=7615
CONFIG_RT_SECOND_CARD_EEPROM="flash"
修改之后编译没有问题，但是刷机之后依然只有一个7615在工作

**Comment by hanwckf** [comment]
> ```
> # 2nd Wireless Interface
> #
> # CONFIG_RT_SECOND_IF_NONE is not set
> # CONFIG_RT_SECOND_IF_RT3352_INIC is not set
> # CONFIG_RT_SECOND_IF_RT3090 is not set
> # CONFIG_RT_SECOND_IF_RT5392 is not set
> # CONFIG_RT_SECOND_IF_RT5592 is not set
> # CONFIG_RT_SECOND_IF_RT3593 is not set
> # CONFIG_RT_SECOND_IF_MT7610E is not set
> # CONFIG_RT_SECOND_IF_MT7602E is not set
> # CONFIG_RT_SECOND_IF_MT7612E is not set
> # CONFIG_RT_SECOND_IF_MT7603E is not set
> CONFIG_RT_SECOND_IF_MT7615E=y
> # CONFIG_RT_SECOND_IF_RANGE_2GHZ is not set
> CONFIG_RT_SECOND_IF_RANGE_5GHZ=y
> CONFIG_RT_SECOND_IF_EEPROM_FLASH=y
> # CONFIG_RT_SECOND_IF_EEPROM_EFUSE is not set
> # CONFIG_RT_SECOND_IF_EEPROM_PROM is not set
> CONFIG_RT_SECOND_IF_RF_OFFSET=0x48000
> CONFIG_RT_SECOND_CARD=7615
> CONFIG_RT_SECOND_CARD_EEPROM="flash"
> ```
> 修改之后编译没有问题，但是刷机之后依然只有一个7615在工作

这...按理来说这样配置会出现第二个7615，你```ifconfig -a```看看有多少个ra/rax/ray之类的东西，然后分别尝试up一下？（如```ifconfig ray0 up```）；如果搞不定的话再考虑把机器提供给我

**Comment by xseven007** [comment]
ifconfig -a 之后，从显示的接口来看，ra0是5G的接口，然而up之后无效。 rax0是2.4G的接口，正常使用。会不会是因为硬件地址找不对呢？

**Comment by xseven007** [comment]
尝试修改/trunk/usr/share/netutils.h里的配置，发现rax0确实是2.4G，然后如果设置成
#define IFNAME_5G_MAIN    "rai0"
就会导致2.4G打不开，并且必须手动对ra0这个端口进行up不然rai0找不到。太奇怪。

**Comment by hanwckf** [comment]
ifconfig 能出来ra0和rax0但是其中启动失败……这个我也不太清楚为何。那个shutils.h里面定义的接口名就是给rc操作ifconfig用的，和你手动在命令行里ifconfig up是一样的

**Comment by xseven007** [comment]
修改K2P的配置文件，重新制作了AC860的配置文件，这样编译出来的固件就会找不到2.4G，这个是其他地方有对K2P进行了特殊定义吗？明天我重新做一个直接修改K2P的配置的，不自己弄配置文件。试试看，如果成功可能就是其他的地方的问题了

**Comment by xseven007** [comment]
实测了一下，2.4G的interface是rax0，5G的是rai0。然后用K2P的配置修改来编译的话，rax0和rai0无法自己启动，然后必须手动启动ra0才能去启动rax0；然而手动启动rax0之后没有rai0。5G不能用。如果自己仿照K2P的写配置文件，然后修改interface，编译AC860。依然是通过ifconfig -a找不到rax0和rai0.必须手动先启动ra0才能找到rax和rai。然而手动启动ra0之后。rax和rai可以手动启动了，但是2.4G无信号。

**Comment by xseven007** [comment]
@hanwckf 研究了很久，不成功，能不能把地址发邮件给我，我快递过去给你那边看一下是什么情况。

**Comment by hanwckf** [comment]
> @hanwckf 研究了很久，不成功，能不能把地址发邮件给我，我快递过去给你那边看一下是什么情况。

好的，不过现在刚开学比较忙，过一个星期才有时间弄，把你的邮箱告诉我吧

**Comment by xseven007** [comment]
@hanwckf 同样是开学，也是比较忙，邮箱就算GitHub上的邮箱。谢啦
