### ISSUE TITLE
工具链中MPFR编译错误

### ISSUE THREAD

**Issue by texchan** [hanwckf/rt-n56u#203]
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[ERROR]    make[3]: *** [check.lo] Error 126
[ERROR]    make[3]: *** Waiting for unfinished jobs....
[ERROR]    make[2]: *** [all] Error 2
[ERROR]    make[1]: *** [all-recursive] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing MPFR for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_mpfr_backend[scripts/build/companion_libs/110-mpfr.sh@125]
[ERROR]  >>        called from: do_mpfr_for_host[scripts/build/companion_libs/110-mpfr.sh@79]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/manual/B_Known_issues.md'
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 3:18.22)
[03:20] / ct-ng:261: recipe for target 'build' failed

**Comment by hanwckf** [comment]
请使用预编译的工具链
