### ISSUE TITLE
可以增加trojan上网方式吗？

### ISSUE THREAD

**Issue by mia0x75** [hanwckf/rt-n56u#208]
https://github.com/trojan-gfw/
体积也非常小。

**Comment by hanwckf** [comment]
这个要处理libboost，以后有空会看一下

**Comment by maskedeken** [comment]
这个估计比较难，trojan的语法用了c++11，但是rt-n56u提供的toolchain不支持c++11

**Comment by chchia** [comment]
如能增加就太好了，运行占用内存比v2ray小，稳定速度也快。

mi-nano就不能运行v2ray因为内存只有64MB，用openwrt就能稳定运行trojan.

**Comment by maskedeken** [comment]
> 
> 
> 如能增加就太好了，运行占用内存比v2ray小，稳定速度也快。
> 
> mi-nano就不能运行v2ray因为内存只有64MB，用openwrt就能稳定运行trojan.

可以用我编译的mipsel版本，不依赖其他库，放在老毛子上可以单独运行
[https://github.com/maskedeken/trojan-gfw](url)

**Comment by mia0x75** [comment]
> > 如能增加就太好了，运行占用内存比v2ray小，稳定速度也快。
> > mi-nano就不能运行v2ray因为内存只有64MB，用openwrt就能稳定运行trojan.
> 
> 可以用我编译的mipsel版本，不依赖其他库，放在老毛子上可以单独运行
> https://github.com/maskedeken/trojan-gfw

```
    "ssl": {
        "verify": false,
```
相同的配置，在路由上需要跳过证书验证SOCK5才能有效。否则
```
[2020-01-14 15:37:05] [WARN] trojan service (client) started at 0.0.0.0:1080
[2020-01-14 15:37:07] [ERROR] 192.168.2.169:62560 SSL handshake failed with www.domain.com:443: certificate verify failed
```

官方release的Linux版在Linux下，相同配置没有证书问题。

**Comment by maskedeken** [comment]
> 
> 
> > > 如能增加就太好了，运行占用内存比v2ray小，稳定速度也快。
> > > mi-nano就不能运行v2ray因为内存只有64MB，用openwrt就能稳定运行trojan.
> > 
> > 
> > 可以用我编译的mipsel版本，不依赖其他库，放在老毛子上可以单独运行
> > https://github.com/maskedeken/trojan-gfw
> 
> ```
>     "ssl": {
>         "verify": false,
> ```
> 
> 相同的配置，在路由上需要跳过证书验证SOCK5才能有效。否则
> 
> ```
> [2020-01-14 15:37:05] [WARN] trojan service (client) started at 0.0.0.0:1080
> [2020-01-14 15:37:07] [ERROR] 192.168.2.169:62560 SSL handshake failed with www.domain.com:443: certificate verify failed
> ```
> 
> 官方release的Linux版在Linux下，相同配置没有证书问题。

那是因为你的路由器没有安装ca root的证书，一般路由器因为空间太小都不会安装，verify置为false是一个办法，另一个办法是在参数中指定证书

**Comment by mia0x75** [comment]
@maskedeken 能否把代码也传上来，供ROM作者整合参考。

**Comment by maskedeken** [comment]
> 
> 
> @maskedeken 能否把代码也传上来，供ROM作者整合参考。

代码就是官方的代码，只是没用老毛子自带的toolchain编译而已

**Comment by mia0x75** [comment]
作者不是说有依赖boost吗，misple怎么编译这个依赖，还有编译哪几个模块。

**Comment by MeIsReallyBa** [comment]
> > > > 如能增加就太好了，运行占用内存比v2ray小，稳定速度也快。
> > > > mi-nano就不能运行v2ray因为内存只有64MB，用openwrt就能稳定运行trojan.
> > > 
> > > 
> > > 可以用我编译的mipsel版本，不依赖其他库，放在老毛子上可以单独运行
> > > https://github.com/maskedeken/trojan-gfw
> > 
> > 
> > ```
> >     "ssl": {
> >         "verify": false,
> > ```
> > 
> > 
> > 相同的配置，在路由上需要跳过证书验证SOCK5才能有效。否则
> > ```
> > [2020-01-14 15:37:05] [WARN] trojan service (client) started at 0.0.0.0:1080
> > [2020-01-14 15:37:07] [ERROR] 192.168.2.169:62560 SSL handshake failed with www.domain.com:443: certificate verify failed
> > ```
> > 
> > 
> > 官方release的Linux版在Linux下，相同配置没有证书问题。
> 
> 那是因为你的路由器没有安装ca root的证书，一般路由器因为空间太小都不会安装，verify置为false是一个办法，另一个办法是在参数中指定证书

试了下好像只能用到cpu的一个线程？

**Comment by shihuaxing** [comment]
你们最后是怎么配置的? 能用trojan了吗?
