### ISSUE TITLE
opkg会导致内核崩溃，entware无法正常使用

### ISSUE THREAD

**Issue by CHN-MAX** [hanwckf/rt-n56u#217]
作者您好，
型号为JCG-836PRO
USB3.0已关闭，使用正常方法无法安装opkg（直接崩掉）
望修复，感谢
Dec 22 17:02:54 kernel: Process opkg (pid: 806, threadinfo=8d9e6000, task=8fd62098, tls=777294a0)
Dec 22 17:02:54 kernel: Stack : 00000000 81198b60 afa60020 afa50024 8e82001c 24130001 00000002 10000002
Dec 22 17:02:54 kernel:         8f8500c0 fffffffc 8e5b0800 00000001 00000000 00000004 8ed10c00 8f85a3c0
Dec 22 17:02:54 kernel:         80308a88 80308ab0 80308aa4 8db359f8 00000000 00000000 000000b0 00000000
Dec 22 17:02:54 kernel:         8d9e7cb8 8d9e7cc0 0058219f 00000000 811b45a0 8da2d000 81198b60 8cc5b000
Dec 22 17:02:54 kernel:         8f9283f0 8e5b0800 0000000c 000000b0 000000b0 8f8f62c8 0000219f 8e5b0000
Dec 22 17:02:54 kernel:         ...
Dec 22 17:02:54 kernel: Call Trace:[<8db359f8>] 0x8db359f8
Dec 22 17:02:54 kernel: [<8db18e2c>] 0x8db18e2c
Dec 22 17:02:54 kernel: [<8db18de4>] 0x8db18de4
Dec 22 17:02:54 kernel: [<8db00340>] 0x8db00340
Dec 22 17:02:54 kernel: [<8db01928>] 0x8db01928
Dec 22 17:02:54 kernel: [<8db003f4>] 0x8db003f4
Dec 22 17:02:54 kernel: [<8db20000>] 0x8db20000
Dec 22 17:02:54 kernel: [<8db30000>] 0x8db30000
Dec 22 17:02:54 kernel: [<8db278f8>] 0x8db278f8
Dec 22 17:02:54 kernel: [<8db24818>] 0x8db24818
Dec 22 17:02:54 kernel: [<800d4368>] 0x800d4368
Dec 22 17:02:54 kernel: [<8db2b2c0>] 0x8db2b2c0
Dec 22 17:02:54 kernel: [<8da80a34>] 0x8da80a34
Dec 22 17:02:54 kernel: [<800d0000>] 0x800d0000
Dec 22 17:02:54 kernel: [<8db0c55c>] 0x8db0c55c
Dec 22 17:02:54 kernel: [<8db29de8>] 0x8db29de8
Dec 22 17:02:54 kernel: [<8db0c55c>] 0x8db0c55c
Dec 22 17:02:54 kernel: [<8db0ca28>] 0x8db0ca28
Dec 22 17:02:54 kernel: [<8db16658>] 0x8db16658
Dec 22 17:02:54 kernel: [<800be028>] 0x800be028
Dec 22 17:02:54 kernel: [<800b9df8>] 0x800b9df8
Dec 22 17:02:54 kernel: [<800b3418>] 0x800b3418
Dec 22 17:02:54 kernel: [<800babbc>] 0x800babbc
Dec 22 17:02:54 kernel: [<8db01f54>] 0x8db01f54
Dec 22 17:02:54 kernel: [<800a5c1c>] 0x800a5c1c
Dec 22 17:02:54 kernel: [<800a24fc>] 0x800a24fc
Dec 22 17:02:54 kernel: [<800a2610>] 0x800a2610
Dec 22 17:02:54 kernel: [<800137dc>] 0x800137dc
Dec 22 17:02:54 kernel: Code: 0043001a  00002010  00001012 
Dec 22 17:02:54 kernel:  03c2f021  3c028030  afa20038  3c028031  0000b825 
Dec 22 17:02:54 kernel: ---[ end trace 830e489693a36acc ]---

**Comment by valeramalko** [comment]
router NEWIFI 3
also an error when installing packages of enware if the drive is formatted in ex4.
If the drive is formatted in ext3, then there are no problems
```
Dec 22 20:09:53 Samba Server: daemon is started
Dec 22 20:09:53 opt-start.sh: call /opt/etc/init.d
Dec 22 20:09:57 NTP Client: Synchronizing time to ntp5.stratum1.ru.
Dec 22 20:32:32 NTP Client: System time changed, offset: 1353.508024s
Dec 22 20:32:35 login[623]: root login on 'pts/0'
Dec 22 20:32:52 kernel: do_cpu invoked from kernel context![#1]:
Dec 22 20:32:52 kernel: Cpu 2
Dec 22 20:32:52 kernel: $ 0   : 00000000 00000001 00000000 9b882190
Dec 22 20:32:52 kernel: $ 4   : 9b8c1b24 00000001 803405b8 00000061
Dec 22 20:32:52 kernel: $ 8   : 9b88219c 00000018 fffffffc 9b8821c4
Dec 22 20:32:52 kernel: $12   : 9b91b904 00000001 fffffffe 00000078
Dec 22 20:32:52 kernel: $16   : 9b07cc00 9a6359f8 9b07cc00 8102cc40
Dec 22 20:32:52 kernel: $20   : 00000061 00000000 9aa11b80 9b8bf830
Dec 22 20:32:52 kernel: $24   : 00000018 99ce0898                  
Dec 22 20:32:52 kernel: $28   : 9aa10000 9aa11b58 9a640000 9aa11b88
Dec 22 20:32:52 kernel: Hi    : 00000003
Dec 22 20:32:52 kernel: Lo    : 00000030
Dec 22 20:32:52 kernel: epc   : 9aa11b98 0x9aa11b98
Dec 22 20:32:52 kernel:     Tainted: G           O
Dec 22 20:32:52 kernel: ra    : 9aa11b88 0x9aa11b88
Dec 22 20:32:52 kernel: Status: 1100fc03    KERNEL EXL IE 
Dec 22 20:32:52 kernel: Cause : 1080002c
Dec 22 20:32:52 kernel: PrId  : 0001992f (MIPS 1004Kc)
Dec 22 20:32:52 kernel: Modules linked in: rt_timer_wdg hw_nat nf_nat_ftp nf_conntrack_ftp ext4 jbd2 mbcache ip_set_hash_net(O) ip_set_hash_mac(O) ip_set_hash_ip(O) xt_set(O) ip_set(O) nfnetlink xhci_hcd usb_storage usblp mt76x3_ap mt76x2_ap
Dec 22 20:32:52 kernel: Process opkg (pid: 694, threadinfo=9aa10000, task=9bcec928, tls=77bb94a0)
Dec 22 20:32:52 kernel: Stack : 9b8f52f8 00000000 81338e00 99c70c00 81338e00 99c70800 9b91b900 9a53d000
Dec 22 20:32:52 kernel:         0000000a 00000061 00000061 9b925108 000016d7 9b07c800 9a618e2c 9a640000
Dec 22 20:32:52 kernel:         00000000 00000000 000c36d9 9a618de4 000c36d8 9a600340 9a601928 9a6003f4
Dec 22 20:32:52 kernel:         9a620000 9a630000 00000000 9a7ae680 9b8f59a0 00000000 9b8f5924 fffffffe
Dec 22 20:32:52 kernel:         00000000 9b8bf830 00000000 9a6278f8 9a64111c 9b8f59a0 99ce8ba4 9b8bf830
Dec 22 20:32:52 kernel:         ...
Dec 22 20:32:52 kernel: Call Trace:[<9a618e2c>] 0x9a618e2c
Dec 22 20:32:52 kernel: [<9a618de4>] 0x9a618de4
Dec 22 20:32:52 kernel: [<9a600340>] 0x9a600340
Dec 22 20:32:52 kernel: [<9a601928>] 0x9a601928
Dec 22 20:32:52 kernel: [<9a6003f4>] 0x9a6003f4
Dec 22 20:32:52 kernel: [<9a620000>] 0x9a620000
Dec 22 20:32:52 kernel: [<9a630000>] 0x9a630000
Dec 22 20:32:52 kernel: [<9a6278f8>] 0x9a6278f8
Dec 22 20:32:52 kernel: [<99ce8ba4>] 0x99ce8ba4
Dec 22 20:32:52 kernel: [<9a624818>] 0x9a624818
Dec 22 20:32:52 kernel: [<800d4368>] 0x800d4368
Dec 22 20:32:52 kernel: [<9a62b2c0>] 0x9a62b2c0
Dec 22 20:32:52 kernel: [<9a619e20>] 0x9a619e20
Dec 22 20:32:52 kernel: [<9a619bd8>] 0x9a619bd8
Dec 22 20:32:52 kernel: [<99ce0a34>] 0x99ce0a34
Dec 22 20:32:52 kernel: [<800d0000>] 0x800d0000
Dec 22 20:32:52 kernel: [<9a60c55c>] 0x9a60c55c
Dec 22 20:32:52 kernel: [<9a619e20>] 0x9a619e20
Dec 22 20:32:52 kernel: [<9a619bd8>] 0x9a619bd8
Dec 22 20:32:52 kernel: [<9a629de8>] 0x9a629de8
Dec 22 20:32:52 kernel: [<9a619e20>] 0x9a619e20
Dec 22 20:32:52 kernel: [<9a619bd8>] 0x9a619bd8
Dec 22 20:32:52 kernel: [<80081e40>] 0x80081e40
Dec 22 20:32:52 kernel: [<9a619c3c>] 0x9a619c3c
Dec 22 20:32:52 kernel: [<9a60f248>] 0x9a60f248
Dec 22 20:32:52 kernel: [<9a60a528>] 0x9a60a528
Dec 22 20:32:52 kernel: [<800c0320>] 0x800c0320
Dec 22 20:32:52 kernel: [<800a2ca0>] 0x800a2ca0
Dec 22 20:32:52 kernel: [<800bc46c>] 0x800bc46c
Dec 22 20:32:52 kernel: [<9a602e00>] 0x9a602e00
Dec 22 20:32:52 kernel: [<800a29b8>] 0x800a29b8
Dec 22 20:32:52 kernel: [<800b31ec>] 0x800b31ec
Dec 22 20:32:52 kernel: [<800b3ac0>] 0x800b3ac0
Dec 22 20:32:52 kernel: [<80030000>] 0x80030000
Dec 22 20:32:52 kernel: [<800b3f28>] 0x800b3f28
Dec 22 20:32:52 kernel: [<800c1170>] 0x800c1170
Dec 22 20:32:52 kernel: [<800ae874>] 0x800ae874
Dec 22 20:32:52 kernel: [<800a3ad4>] 0x800a3ad4
Dec 22 20:32:52 kernel: [<800a24fc>] 0x800a24fc
Dec 22 20:32:52 kernel: [<800137dc>] 0x800137dc
Dec 22 20:32:52 kernel: Code: 9b07c800  9a618e2c  9a640000 
Dec 22 20:32:52 kernel:  00000000  000c36d9  9a618de4  000c36d8  9a600340 
Dec 22 20:32:52 kernel: ---[ end trace 1e135708c55afa99 ]---
```

**Comment by hanwckf** [comment]
我在HC5761A和AC860M上尝试过，并没有遇到相同的情况，请问楼上两位有没有同时启用samba？可以多试几次

**Comment by valeramalko** [comment]
> 
> 
> 我在HC5761A和AC860M上尝试过，并没有遇到相同的情况，请问楼上两位有没有同时启用samba？可以多试几次

yes, Samba enabled at the same time

**Comment by CHN-MAX** [comment]
> 我在HC5761A和AC860M上尝试过，并没有遇到相同的情况，请问楼上两位有没有同时启用samba？可以多试几次

samba是在启动状态的，在usb3.0下拷文件大概率也会导致内核报错

**Comment by mqcing** [comment]
我也有这样的问题，samba没有启动，新三D2版

**Comment by lyolic** [comment]
I have the same issue with opkg

**Comment by lyolic** [comment]
I confirm, that using ext3 resolves the problem

**Comment by valeramalko** [comment]
here http://4pda.ru/forum/index.php?s=&showtopic=714487&view=findpost&p=94321686 a solution was proposed on the problem of working with ext4, I have not checked it myself yet

**Comment by hanwckf** [comment]
> here http://4pda.ru/forum/index.php?s=&showtopic=714487&view=findpost&p=94321686 a solution was proposed on the problem of working with ext4, I have not checked it myself yet

Thanks a lot!

**Comment by hanwckf** [comment]
@CHN-MAX @lyolic @mqcing 
已经在 https://github.com/hanwckf/rt-n56u/commit/76bfb2371d5dbffb370440fc03b9963b9ee8e6ce 尝试修复，可以再试一下

**Comment by CHN-MAX** [comment]
问题已解决，非常感谢
