### ISSUE TITLE
nfs无法正常使用，是否与portmap有关？

### ISSUE THREAD

**Issue by kkjoy** [hanwckf/rt-n56u#224]
https://github.com/hanwckf/rt-n56u/blob/master/trunk/user/nfs-utils/nfs-utils-1.2.8/README
上述文档中说明：  "portmap" must be running before any NFS services (server or
   client) are started.
在原版padavan的源码中也有portmap。
但是本分支似乎没有portmap。使用android版vlc直接输入地址无法连接nfs，kodi中也无法正常连接。望修正。

**Comment by cnazev** [comment]
@kkjoy 你好 这个问题你那解决了吗？

**Comment by kkjoy** [comment]
> @kkjoy 你好 这个问题你那解决了吗？
我换回荒野的固件当二级了
