### ISSUE TITLE
编译openssl-1.0.2t错误

### ISSUE THREAD

**Issue by PaPerseller** [hanwckf/rt-n56u#258]
路由器机型：k2p
编译固件：k2p_nano-5.0
编译系统：manjaro 和 wsl ubuntu18.04
编译问题：均出现编译 openssl-1.0.2t 错误
错误提示：make[2]: 进入目录“/opt/rt-n56u/trunk/libs/libssl”
( if [ ! -f openssl-1.0.2t.tar.gz ]; then \
        wget -t5 --timeout=20 --no-check-certificate -O openssl-1.0.2t.tar.gz https://www.openssl.org/source/openssl-1.0.2t.tar.gz; \
fi )
( if [ ! -d openssl-1.0.2t ]; then \
        tar xzf openssl-1.0.2t.tar.gz; \
        patch -d openssl-1.0.2t -p1 -i ../openssl-orig.patch; \
fi )
( if [ -f ./config_done ]; then \
        echo "the same configuration"; \
else \
        make configure && touch config_done; \
fi )
the same configuration
make -C openssl-1.0.2t depend
make[3]: 进入目录“/opt/rt-n56u/trunk/libs/libssl/openssl-1.0.2t”
Makefile is older than Makefile.org, Configure or config.
Reconfigure the source tree (via './config' or 'perl Configure'), please.
make[3]: *** [Makefile:412：Makefile] 错误 1
make[3]: 离开目录“/opt/rt-n56u/trunk/libs/libssl/openssl-1.0.2t”
make[2]: *** [Makefile:35：all] 错误 2
make[2]: 离开目录“/opt/rt-n56u/trunk/libs/libssl”
make[1]: *** [Makefile:236：all] 错误 2
make[1]: 离开目录“/opt/rt-n56u/trunk/libs”
make: *** [Makefile:202：libs_only] 错误 2

**Comment by hcym** [comment]
mtk不知道，arm和x86都可以通过

**Comment by xratzh** [comment]
十几天之前vps上面编译的，编译了k2p、miwifi、hc5761a，一个命令，nohup等他自己编译，过一段时间上vps拖到本地就OK了。都没问题。看你这个，应该是make的环境没调试好，找个空白文件重新搞吧

**Comment by PaPerseller** [comment]
> 十几天之前vps上面编译的，编译了k2p、miwifi、hc5761a，一个命令，nohup等他自己编译，过一段时间上vps拖到本地就OK了。都没问题。看你这个，应该是make的环境没调试好，找个空白文件重新搞吧

您的方法之前已试，将所有文件全部删除，重新搞了编译环境和编译链后，仍然是这个问题，这也是换到 WSL 上尝试编译的原因。

**Comment by PaPerseller** [comment]
在全新安装的kali linux以及在manjaro上完全删除rt-n56u后重装编译成功，估计是旧环境造成的编译错误
