### ISSUE TITLE
NEWIFI-D2 Cant Update Due to Wrong ProductID

### ISSUE THREAD

**Issue by sperglord8008s** [hanwckf/rt-n56u#259]
Trying to use WebUI Firmware Update - Error Log.

Feb  2 04:07:37 httpd[571]: Firmware update: Incorrect image ProductID: NEWIFI3! Expected is NEWIFI-D2.

Updating from Firmware

"3.4.3.9-099_20181020-1912" 
 [Upstream commit: e6f4533]
Build by 0x48595744 build rev: 32dd25d

**Comment by valeramalko** [comment]
use Breed bootloader for firmware

**Comment by sperglord8008s** [comment]
many thanks house cat
