### ISSUE TITLE
pls make sure applied patches are consistent

### ISSUE THREAD

**Issue by i3roly** [hanwckf/rt-n56u#269]
hi @hanwckf,

i noticed, for example that, patch 3 from https://github.com/hanwckf/openwrt-mt7615/tree/master/patches has not been applied to 5.0.3.0.

i know most patches there are minor, and you are probably a little overwhelmed with all the maintenance for this large driver, but i was going to ask that you make sure all patches are applied just so users aren't confused.

small issue and i think you'll fix it.

**Comment by hanwckf** [comment]
This patch is only for openwrt, See https://github.com/Nossiac/mtk-openwrt-feeds/issues/55#issuecomment-401537666

**Comment by hanwckf** [comment]
But I think applying this patch in Padavan would not cause any exception.

**Comment by i3roly** [comment]
ok no problem.

can we try to tackle problem with RX  errors and only 600 MB/s on 2.4ghz interface?

please help!
