### ISSUE TITLE
hanwckf 快来看有BUG，VPN服务设计有问题吧

### ISSUE THREAD

**Issue by chenxudong2020** [hanwckf/rt-n56u#271]
安装你的教程说的 设置此参数可以控制页面上的VPN功能是否显示，而我设置为CONFIG_FIRMWARE_WEBUI_HIDE_VPN =n
编译好了 但是没有显示VPN菜单
是不是代码中这个功能已经被删除了
如果被删除了  那配置.config文件中的OPENVPN怎么使用了
我记得这个功能需要配合Padavan自带的VPN功能使用

**Comment by ywycd** [comment]
看commit是移到更多菜单。https://github.com/hanwckf/rt-n56u/pull/251。我自编译是精简的所以没找到。

**Comment by chenxudong2020** [comment]
> 看commit是移到更多菜单。#251   网络地图-地球图标，more config 里可以选择

CONFIG_FIRMWARE_WEBUI_HIDE_VPN =n 这个在哪里配置了？还有固件会默认启用ss和dns-forwarder就算配置里面关了 页面还是会显示菜单

**Comment by ywycd** [comment]
[img]http://i2.tiimg.com/500480/1b1b0c3202e70527.png[/img]
源码更改后这个HIDE_VPN=n配置不起作用，照这个路径可以找到。选no应该就没了，我也是自己编译没有。重置出厂试试
