### ISSUE TITLE
使用最新源码构建的固件，在开启IPV6的情况下，PPPoE 联网状态下无 VPN 菜单入口，关闭IPV6功能后菜单面板才出现。

### ISSUE THREAD

**Issue by ningsibuqu** [hanwckf/rt-n56u#276]
如图，无更多设置，设备是K2P。
![](https://user-images.githubusercontent.com/51028975/74903203-42b41080-53e3-11ea-85c4-71ddb5f80cde.png)

**Comment by ywycd** [comment]
![Markdown](http://i2.tiimg.com/500480/1b1b0c3202e70527.png)
参考下

**Comment by ningsibuqu** [comment]
> ![Markdown](https://camo.githubusercontent.com/890252bcc7b91895c99e422b9d7b3500feb173a2/687474703a2f2f69322e7469696d672e636f6d2f3530303438302f316231623063333230326537303532372e706e67)
> 参考下
懂了，刚刚试了一下，是因为开了IPV6，所以更多设置不见了。
不开IPV6就有更多设置。

**Comment by chenxudong2020** [comment]
> 参考下
> 
> 懂了，刚刚试了一下，是因为开了IPV6，所以更多设置不见了。
> 不开IPV6就有更多设置。
这个问题我明白了 在问个问题  1.在编译时候 去掉了B70.Config DNSFarwarder和SS但是编译成功了 页面还是有这个菜单，点击进去页面打开是空白的 这算BUG吧，2.编译出来的固件ping路由网关有超时的现象 这个怎么处理

**Comment by hanwckf** [comment]
https://github.com/hanwckf/rt-n56u/commit/a2b295895491a787cc35207a25d454fb987d3bd7
