### ISSUE TITLE
出现吓人日志 

### ISSUE THREAD

**Issue by chenxudong2020** [hanwckf/rt-n56u#277]
Feb 27 15:54:37 kernel: 2.4GHz AP ageout ce:81:da:71:15:c8 after 240-sec silence
Feb 27 16:23:33 kernel: 2.4GHz AP ageout 60:36:dd:5c:15:57 after 240-sec silence

日志出现上述东西 怪吓人 怎么回事 要瓦特了吗

**Comment by itfish92** [comment]
Please take this board seriously
