### ISSUE TITLE
恳请指教几个问题

### ISSUE THREAD

**Issue by TinkMingKing** [hanwckf/rt-n56u#282]
水平有限，恳请指教

- 1.是否有办法预置cron服务的配置文件，该如何做？
- 2.如何修改logo？我看www下的[logo图](https://github.com/hanwckf/rt-n56u/blob/master/trunk/user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png)和编译出来的logo不一样，看到过这样的padavan的logo，原图在何处？![](https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=2508276015,3563754673&fm=15&gp=0.jpg)

- 3.[default.c](https://github.com/hanwckf/rt-n56u/blob/master/trunk/user/shared/defaults.c)中所对应的参数在何处查看？虽有注释，但不完整，参数具体对应的选项在何处查看？

**Comment by hanwckf** [comment]
1. 可以在mtd_storage.sh脚本里初始化crontab
2. 这是hiboy的固件
3. 这个没有统一的方法

**Comment by TinkMingKing** [comment]
好的谢谢
