### ISSUE TITLE
AC1200GU 时钟慢，例如web界面显示“运行时间”过了半小时，实际现实中却是已经过了一小时了

### ISSUE THREAD

**Issue by darwin-lu-hotmail** [hanwckf/rt-n56u#284]
AC1200GU 时钟慢，例如web界面显示“运行时间”过了半小时，实际现实中却是已经过了一小时了

**Comment by hanwckf** [comment]
这看起来是严重的问题，不清楚是不是晶振的关系，查了下AC1200GU的拆机图，板子正面没看到有MT7621的晶振。

**Comment by darwin-lu-hotmail** [comment]
> 这看起来是严重的问题，不清楚是不是晶振的关系，查了下AC1200GU的拆机图，板子正面没看到有MT7621的晶振。

用的是hiboy的padavan，3.4.3.9-099_20-03-1版本，看到他fork了你的代码所以想问下，也跟他反映过这个问题了，怀疑可能是华硕uboot里给超频了，如下百度盘里分享的启动log看到cpu频率是1100MHz，代码配置里有force 900MHz的选项但是没打开。
链接: https://pan.baidu.com/s/1LF3aUM9T5DrfPIOAmN7Svg 提取码: r7wn

恩山论坛上也有人发现了这个问题 https://www.right.com.cn/forum/thread-1780644-1-1.html

**Comment by darwin-lu-hotmail** [comment]
AC1200GU 没有breed用，原来运行的是华硕官方固件，后来用华硕救援模式刷入的padavan固件

**Comment by hanwckf** [comment]
> AC1200GU 没有breed用，原来运行的是华硕官方固件，后来用华硕救援模式刷入的padavan固件

官方超频了？那可能就是这个原因，想办法刷个breed进去让它恢复默认的880MHz估计时钟就正常了

**Comment by darwin-lu-hotmail** [comment]
> > AC1200GU 没有breed用，原来运行的是华硕官方固件，后来用华硕救援模式刷入的padavan固件
> 
> 官方超频了？那可能就是这个原因，想办法刷个breed进去让它恢复默认的880MHz估计时钟就正常了

目前 AC1200GU 没有专用breed只能用救援模式，看到AC1200GU代码配置里有下面的配置选项，是否打开就可以正常了? 目前可否给默认给打开这个选项呢

### Force MT7621 CPU clock to 900MHz (override Uboot settings)
#CONFIG_FIRMWARE_CPU_900MHZ=y

**Comment by hanwckf** [comment]
可以试试，不过建议你备份原厂uboot之后尝试刷个7621的breed进去

**Comment by darwin-lu-hotmail** [comment]
> 可以试试，不过建议你备份原厂uboot之后尝试刷个7621的breed进去

尝试改了这个还是没有作用

**Comment by darwin-lu-hotmail** [comment]
> 可以试试，不过建议你备份原厂uboot之后尝试刷个7621的breed进去



> > 可以试试，不过建议你备份原厂uboot之后尝试刷个7621的breed进去
> 
> 尝试改了这个还是没有作用

就是改 CONFIG_FIRMWARE_CPU_900MHZ=y

**Comment by darwin-lu-hotmail** [comment]
发现打开 CONFIG_RALINK_SYSTICK_COUNTER 和 CONFIG_GENERIC_CLOCKEVENTS_BROADCAST 后时间就正常了

[https://github.com/darwin-lu-hotmail/rt-n56u/commit/d5dc8e6b39d8b7bbe00c8a12a84b34b597506187](url)

**Comment by hanwckf** [comment]
> 发现打开 CONFIG_RALINK_SYSTICK_COUNTER 和 CONFIG_GENERIC_CLOCKEVENTS_BROADCAST 后时间就正常了
> 
> [darwin-lu-hotmail@d5dc8e6](https://github.com/darwin-lu-hotmail/rt-n56u/commit/d5dc8e6b39d8b7bbe00c8a12a84b34b597506187)

好
