### ISSUE TITLE
CONFIG_FIRMWARE_WEBUI_HIDE_VPN=y无效

### ISSUE THREAD

**Issue by wukuili** [hanwckf/rt-n56u#291]
环境：newifi-mini 
自己修改了config文件，在文件最后添加了CONFIG_FIRMWARE_WEBUI_HIDE_VPN=y 
然后再Ubuntu18.04中编译
使用在线升级方式升级后，菜单上仍然没有出现openvpn，请问怎么回事。
另外我把ssserver也设置成了y .也没有出现ssserver

**Comment by chenxudong2020** [comment]
OpenVPN隐藏了  在首页 地球那个图片 右下角 更多设置里 大佬有时间在readMe中解释下吧 不然很多问的

**Comment by wukuili** [comment]
> OpenVPN隐藏了 在首页 地球那个图片 右下角 更多设置里 大佬有时间在readMe中解释下吧 不然很多问的

多谢大佬 我刷新最新的试试

**Comment by wukuili** [comment]
> OpenVPN隐藏了 在首页 地球那个图片 右下角 更多设置里 大佬有时间在readMe中解释下吧 不然很多问的

大佬 我把固件刷到release里面最新的了  但更多设置里面没有openvpn 是不是需要我自己build 然后改config文件吗？
