### ISSUE TITLE
给HC5661A编译出错，不知如何解决

### ISSUE THREAD

**Issue by RebornL** [hanwckf/rt-n56u#3]
编译报错内容如下，请问这是什么原因造成的？
make[2]: Entering directory '/opt/rt-n56u/trunk/libc/uClibc-0.9.33.2'
.config:7: *** missing separator。 停止。
make[2]: Leaving directory '/opt/rt-n56u/trunk/libc/uClibc-0.9.33.2'
Makefile:19: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/libc'
Makefile:185: recipe for target 'libc_only' failed
make: *** [libc_only] Error 2

**Comment by hanwckf** [comment]
请确保```trunk/configs/boards/<机型>```里面的```libc.config```符号连接指向正确
