### ISSUE TITLE
请采用此驱动MT7603E驱动

### ISSUE THREAD

**Issue by chenxudong2020** [hanwckf/rt-n56u#304]
https://github.com/trublemaker/mt7603-4.1.2.0
此驱动是可有效提升newifi3 2.4G无线信号

**Comment by hanwckf** [comment]
> https://github.com/trublemaker/mt7603-4.1.2.0
> 此驱动是可有效提升newifi3 2.4G无线信号

目前mt7603_dev分支已经换成4.1.2.0版本的驱动，但是我手头现在没有7612+7603的机器，你可以先刷附件里上传的固件试一下看看7603是否工作正常；我现在用7611+7603的WDR7300测试正常。

同时尝试修复32M flash reboot失败的问题，可以测试一下看看能否正常重启。


[NEWIFI3_new_7603.trx.zip](https://github.com/hanwckf/rt-n56u/files/4407036/NEWIFI3_new_7603.trx.zip)

**Comment by chenxudong2020** [comment]
我手头有B70 我先编译一版试试在反馈  我想解决的问题是https://www.right.com.cn/forum/thread-3726111-1-1.html

**Comment by Promix953** [comment]
NEWIFI3,编译了一版，工作正常，2.4G的确有提升
[newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)

**Comment by hanwckf** [comment]
> NEWIFI3,编译了一版，工作正常，2.4G的确有提升
> [newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)

非常感谢

**Comment by hanwckf** [comment]
> NEWIFI3,编译了一版，工作正常，2.4G的确有提升
> [newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)

请问reboot现在能正常工作不

**Comment by chenxudong2020** [comment]
B70编译了一般 目前使用正常 中继ping上级路由延迟低 在路由web界面点击重启正常

**Comment by hanwckf** [comment]
> B70编译了一般 目前使用正常 中继ping上级路由延迟低 [在路由web界面点击重启正常](url
> [B70启动日志.txt](https://github.com/hanwckf/rt-n56u/files/4412798/B70.txt)
> )

b70用的是NAND，重启应该都是正常的

**Comment by Promix953** [comment]
> > NEWIFI3,编译了一版，工作正常，2.4G的确有提升
> > [newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)
> 
> 请问reboot现在能正常工作不

reboot工作正常，用了一天，没遇到什么问题
就是log里面很多
```
kernel: RtmpChipOpsHook(474): Not support for HIF_MT yet!
```

**Comment by hanwckf** [comment]
> > > NEWIFI3,编译了一版，工作正常，2.4G的确有提升
> > > [newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)
> > 
> > 
> > 请问reboot现在能正常工作不
> 
> reboot工作正常，用了一天，没遇到什么问题
> 就是log里面很多
> 
> ```
> kernel: RtmpChipOpsHook(474): Not support for HIF_MT yet!
> ```

直接从源码里删除这行输出即可

**Comment by Promix953** [comment]
> > > > NEWIFI3,编译了一版，工作正常，2.4G的确有提升
> > > > [newifi3_mt7603_dev.log](https://github.com/hanwckf/rt-n56u/files/4411472/newifi3_mt7603_dev.log)
> > > 
> > > 
> > > 请问reboot现在能正常工作不
> > 
> > 
> > reboot工作正常，用了一天，没遇到什么问题
> > 就是log里面很多
> > ```
> > kernel: RtmpChipOpsHook(474): Not support for HIF_MT yet!
> > ```
> 
> 直接从源码里删除这行输出即可

这几条应该也是nosie log:
```
Apr  2 00:37:21 kernel: AsicSetRalinkBurstMode(4325): Not support for HIF_MT yet!
Apr  2 00:37:21 kernel: RTMPSetPiggyBack(943): Not support for HIF_MT yet!
Apr  2 00:37:21 kernel: AsicSetTxPreamble(4312): Not support for HIF_MT yet!
Apr  2 00:37:21 kernel: AsicAddSharedKeyEntry(2073): Not support for HIF_MT yet!
```

**Comment by xiaole51** [comment]
怎么从log看出信号有提升?
2.4g有个致命问题是看直播会非常卡.
测速信号80M的时候一样的卡,不知这个驱动能否改善.
晚上测试后反馈.

**Comment by chenxudong2020** [comment]
B70使用了好几天 发现信号强度有提升 但是中继ping上级ssid管理IP掉包严重---不稳定---测速也掉了

以上测试是相对于以前驱动4.1.0.0

**Comment by Promix953** [comment]
> B70使用了好几天 发现信号强度有提升 但是中继ping上级ssid管理IP掉包严重---不稳定---测速也掉了
> 
> 以上测试是相对于以前驱动4.1.0.0

我这边是Newifi3仅作为AP使用，没遇到问题，中继方面没测试

**Comment by xiaole51** [comment]
刚刚测试了这个测试包. NEWIFI3_new_7603.trx.zip
2.4G有了质的改善,原来的不管信号多强看直播非常卡.
换上后直播非常流畅.弱信号稳定性也得到加强.

现有代码下如何替换为4.1.2?
直接替换驱动目录可否?

**Comment by Promix953** [comment]
> 刚刚测试了这个测试包. NEWIFI3_new_7603.trx.zip
> 2.4G有了质的改善,原来的不管信号多强看直播非常卡.
> 换上后直播非常流畅.弱信号稳定性也得到加强.
> 
> 现有代码下如何替换为4.1.2?
> 直接替换驱动目录可否?

现在的master就是4.1.2.0的了

**Comment by butinhi** [comment]
@hanwckf still have problem with reboot :( newifi3

**Comment by Tony-LYX** [comment]
小白想问一下travis-ci自动构建是不是每天都在编译新固件呀，怎么下载呢？
我自己Ubuntu已经尝试编译了4次，每次都是PSG1218能正常编译，NEWIFI3编译失败，失败信息在简书那个页面下有。
如果自动构建能用，我就试试自动构建的结果了。

**Comment by hanwckf** [comment]
> 小白想问一下travis-ci自动构建是不是每天都在编译新固件呀，怎么下载呢？
> 我自己Ubuntu已经尝试编译了4次，每次都是PSG1218能正常编译，NEWIFI3编译失败，失败信息在简书那个页面下有。
> 如果自动构建能用，我就试试自动构建的结果了。

自动构建是可以用，但是transfer.sh经常抽风，导致固件上传失败。
你把你的报错信息贴到这里来看看吧

**Comment by Tony-LYX** [comment]
错误代码如下，跟我有一样情况的还不止一位网友
```
services_stor.c:(.text+0x24b8): undefined reference to `start_wins'
/opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/lib/gcc/mipsel-linux-uclibc/7.4.0/../../../../mipsel-linux-uclibc/bin/ld: services_stor.c:(.text+0x24bc): undefined reference to `start_wins'
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/opt/rt-n56u/trunk/user/rc'
Makefile:210: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
Makefile:202: recipe for target 'user_only' failed
make: *** [user_only] Error 2
```
简书网址https://www.jianshu.com/p/6b8403cdea46

**Comment by hanwckf** [comment]
> 错误代码如下，跟我有一样情况的还不止一位网友
> 
> ```
> services_stor.c:(.text+0x24b8): undefined reference to `start_wins'
> /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x/lib/gcc/mipsel-linux-uclibc/7.4.0/../../../../mipsel-linux-uclibc/bin/ld: services_stor.c:(.text+0x24bc): undefined reference to `start_wins'
> collect2: error: ld returned 1 exit status
> Makefile:68: recipe for target 'all' failed
> make[2]: *** [all] Error 1
> make[2]: Leaving directory '/opt/rt-n56u/trunk/user/rc'
> Makefile:210: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/opt/rt-n56u/trunk/user'
> Makefile:202: recipe for target 'user_only' failed
> make: *** [user_only] Error 2
> ```
> 
> 简书网址https://www.jianshu.com/p/6b8403cdea46
> 
> 我看Git Acitons好像也挺厉害的，下次试试

你在第二次编译的时候忘记了`./clear_tree_simple`

**Comment by Tony-LYX** [comment]
非常感谢，我用Git Actions编译成功了，这样云编译也还是蛮好的，速度很快不用占用自己的电脑。有个问题想问一下：编译好的包里面，还有RAMdisk Zimage之类的东西，这些是什么呢？

**Comment by chenxudong2020** [comment]
使用此驱动编译的MT7603 2.4G驱动的，麻烦测试下中继速度如何？
测试1 无线中继只接收5G   2.4G发射   手机连接2.4G测速多少
测试2  无线中继只接收2.4G 5G发射   手机连接5G速度多少
测试3   无线桥接 LAN模式 只接收5g  2.4g发射 手机连接2.4G测速多少
测试4   无线桥接 LAN模式 只接收2.4g  5g发射 手机连接5G测速多少
反馈下我的情况 测试编译的是今天最新代码Github Action编译的固件B70
测试1 测试2 测试3 测试4  手机VIVO Y5S  均在同一地点测试 
测试1  2M/s
测试2  中继不成功一直显示获取IP
测试3  0.1M/s基本没速度
测试4  基本没速度
手机VIVO Y5S 直接连接上级SSID 5G 4M/s   2.4G  1M/s
上级路由器是K2 用的padavan固件

**Comment by xiaole51** [comment]
目前驱动很稳定,使用上没什么问题了.
不过内核还是会输出些错误信息.

ICV Error
RMAC_RXD Header Format :RxNormal
ICV Error
RMAC_RXD Header Format :RxNormal
ICV Error
RMAC_RXD Header Format :RxNormal

**Comment by emirefek** [comment]
Can someone help how to integrate it to R2100 firmware?

**Comment by emirefek** [comment]
THIS ISSUE SHOULD BE TAGGED AS CLOSED. LATEST DRIVER ALREADY INCLUDED TO SOURCE:MASTER

**Comment by chenxudong2020** [comment]
目前所有的使用7603驱动都默认是4.1.2.0版本，已经不需要配置也不可以切换成4.1.0.0版本，所以你提出的问题不存在，新版本驱动在newifi3机器上表现好，其他机器发现没有老驱动好，hanwckf是否把驱动做成可以可设置的方式。



---原始邮件---
发件人: "emirefek"<notifications@github.com&gt;
发送时间: 2020年5月1日(周五) 晚上9:01
收件人: "hanwckf/rt-n56u"<rt-n56u@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chenxudong2020"<872603935@qq.com&gt;;
主题: Re: [hanwckf/rt-n56u] 请采用此驱动MT7603E驱动 (#304)




 
THIS ISSUE SHOULD BE TAGGED AS CLOSED. LATEST DRIVER ALREADY INCLUDED TO SOURCE:MASTER

**Comment by ju0594** [comment]
> 目前驱动很稳定,使用上没什么问题了.
> 不过内核还是会输出些错误信息.
> 
> ICV Error
> RMAC_RXD Header Format :RxNormal
> ICV Error
> RMAC_RXD Header Format :RxNormal
> ICV Error
> RMAC_RXD Header Format :RxNormal

是的 我B70的日志里也有这些...
