### ISSUE TITLE
请添加型号Netgear R6850

### ISSUE THREAD

**Issue by den4al** [hanwckf/rt-n56u#307]
请添加Netgear R6850，非常感谢。 https://openwrt.org/toh/hwdata/netgear/netgear_r6850

**Comment by hanwckf** [comment]
网件的NAND机型在没有机器的情况下暂时不会去适配

**Comment by FenghenHome** [comment]
> 网件的NAND机型在没有机器的情况下暂时不会去适配

我们借你机器可以吗，R6800

**Comment by nicefile** [comment]
There are some issues regarding flash mapping on Netgears . Mine is happend to have exacly same map like in OpenWRT but one of developers tried pull the change due to His unit R6260 had different layout.
@hanwckf You could build test images based on hardware definition from OpenWrt  .I volunteer for testing .R6350 R6260 R6850 WAC124 are exacly the same hardware despite antenna differences .

**Comment by nicefile** [comment]
@den4al
Make sure You have nand backup and serial cable to continue:
  I've builded padavan image for testing  .It's based on OpenWrt data  .Referenced padavan B70, mir3g for NAND support and WDR7300 , DIR882 for 7603 and 7615e configuration
It should be able to flash it via
https://github.com/jclehner/nmrpflash 

Or via breed bootloader (R6220 can be used as nand flash  and reset button match )
Below is image and config files used to build 
https://drive.google.com/drive/folders/1-l3KO0J0whLAm14TxKP99wru_izK0nPS?usp=sharing

**Comment by den4al** [comment]
> @den4al
> Make sure You have nand backup and serial cable to continue:
> I've builded padavan image for testing .It's based on OpenWrt data .Referenced padavan B70, mir3g for NAND support and WDR7300 , DIR882 for 7603 and 7615e configuration
> It should be able to flash it via
> https://github.com/jclehner/nmrpflash
> 
> Or via breed bootloader (R6220 can be used as nand flash and reset button match )
> Below is image and config files used to build
> https://drive.google.com/drive/folders/1-l3KO0J0whLAm14TxKP99wru_izK0nPS?usp=sharing

https://github.com/nicefile

**Comment by den4al** [comment]
> @den4al
> Make sure You have nand backup and serial cable to continue:
> I've builded padavan image for testing .It's based on OpenWrt data .Referenced padavan B70, mir3g for NAND support and WDR7300 , DIR882 for 7603 and 7615e configuration
> It should be able to flash it via
> https://github.com/jclehner/nmrpflash
> 
> Or via breed bootloader (R6220 can be used as nand flash and reset button match )
> Below is image and config files used to build
> https://drive.google.com/drive/folders/1-l3KO0J0whLAm14TxKP99wru_izK0nPS?usp=sharing

Thank you man, I will test the time.
