### ISSUE TITLE
Toolchain build failed

### ISSUE THREAD

**Issue by zwypfdsj** [hanwckf/rt-n56u#309]
### System Version
> Ubuntu 18.04.1
### GCC Version
> 7.4.0

### ERROR LOG
> [WARN ]    uClibc-ng: using custom location, no patches applied
[ERROR]    Neither file nor directory: /opt/rt-n56u/toolchain-mipsel/../trunk/libc/uClibc-ng-1.0.32
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoExtractPatch[scripts/functions@2371]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
[ERROR]  >>        called from: CT_ExtractPatch[scripts/functions@2399]
[ERROR]  >>        called from: uClibc_extract[scripts/build/libc.sh@8]
[ERROR]  >>        called from: do_libc_extract[scripts/build/libc.sh@23]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@668]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/manual/B_Known_issues.md'
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 1:53.89)
[01:55] / ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by den4al** [comment]
I have a Toolchain build error too

**Comment by chaohua27** [comment]
Me too.

**Comment by hanwckf** [comment]
> ### System Version
> > Ubuntu 18.04.1
> 
> ### GCC Version
> > 7.4.0
> 
> ### ERROR LOG
> > [WARN ]    uClibc-ng: using custom location, no patches applied
> > [ERROR]    Neither file nor directory: /opt/rt-n56u/toolchain-mipsel/../trunk/libc/uClibc-ng-1.0.32
> > [ERROR]
> > [ERROR]  >>
> > [ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
> > [ERROR]  >>        called in step '(top-level)'
> > [ERROR]  >>
> > [ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
> > [ERROR]  >>        called from: CT_DoExtractPatch[scripts/functions@2371]
> > [ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
> > [ERROR]  >>        called from: CT_ExtractPatch[scripts/functions@2399]
> > [ERROR]  >>        called from: uClibc_extract[scripts/build/libc.sh@8]
> > [ERROR]  >>        called from: do_libc_extract[scripts/build/libc.sh@23]
> > [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@668]
> > [ERROR]  >>
> > [ERROR]  >>  There is a list of known issues, some with workarounds, in:
> > [ERROR]  >>      'docs/manual/B_Known_issues.md'
> > [ERROR]  >>
> > [ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
> > [ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
> > [ERROR]  >> any experimental features. Otherwise, you'll need to debug it
> > [ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
> > [ERROR]  >> preferably, a fix.
> > [ERROR]  >>
> > [ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
> > [ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
> > [ERROR]  >>
> > [ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
> > [ERROR]  >>  Read the bug reporting guidelines here:
> > [ERROR]  >>      http://crosstool-ng.github.io/support/
> > [ERROR]
> > [ERROR]  (elapsed: 1:53.89)
> > [01:55] / ct-ng:261: recipe for target 'build' failed
> > make: *** [build] Error 1

上次删去了不需要重复构建的uclibc源码，所以会导致工具链构建失败。
推荐使用预编译的工具链，参考README.md里面的说明

**Comment by zwypfdsj** [comment]
那我是否可以删掉`trunk/libc/uClibc-ng-1.0.32`的源码，使用官网的`uClibc-ng-1.0.33`的源码来替代，是否需要修改源码呢？

**PS：官网最新版本是 [1.0.33 released 16.02.2020](https://uclibc-ng.org)，但是Github上还是 [1.0.32](https://github.com/wbx-github/uclibc-ng)**

**Comment by hanwckf** [comment]
> ~那我是否可以删掉`trunk/libc/uClibc-ng-1.0.32`的源码，使用官网的`uClibc-ng-1.0.33`的源码来替代，是否需要修改源码呢？~
> 
> **PS：官网最新版本是 [1.0.33 released 16.02.2020](https://uclibc-ng.org)，但是Github上还是 [1.0.32](https://github.com/wbx-github/uclibc-ng)**
> 
> 我试了一下，需要修改
> https://github.com/hanwckf/rt-n56u/blob/e475262725b88b1ac670c59698efa7a1e6ddde1f/toolchain-mipsel/samples/mipsel-linux-uclibc/crosstool.config#L27
> 
> 
> 工具链可以构建成功，就是不知道能否正常编译固件。

可以的

**Comment by xuanwumen** [comment]
请问你们是怎么解决这个问题的呢，是使用预编译工具链 ，仍然出现以上错误

**Comment by Luxuslaerm** [comment]
大佬们，32位的系统怎么破，预编译的好像是64位的
