### ISSUE TITLE
能否适配一下极2-HC5761A

### ISSUE THREAD

**Issue by beyai** [hanwckf/rt-n56u#31]
极2-HC5761A 的芯片方案是 MT7628AN + MT7610EN 好像和 MZ-R13P 一样
GPIO 如下：

GPIOs 0-31, MT7628-GPIO0:
 gpio-1   (hiwifi:green:interne) out lo

GPIOs 32-63, MT7628-GPIO1:
 gpio-37  (hiwifi:green:system ) out hi
 gpio-38  (reset               ) in  hi
 gpio-40  (hiwifi:green:wlan-5p) out lo
 gpio-41  (usb                 ) out lo
 gpio-44  (hiwifi:green:wlan-2p) out hi

GPIOs 64-95, MT7628-GPIO2:

**Comment by hanwckf** [comment]
需要网口次序，这个机器只有三个网口吧...

**Comment by beyai** [comment]
网口次序和HC5661A一样
CONFIG_RAETH_ESW_PORT_WAN=4
CONFIG_RAETH_ESW_PORT_LAN1=3
CONFIG_RAETH_ESW_PORT_LAN2=2
CONFIG_RAETH_ESW_PORT_LAN3=1
CONFIG_RAETH_ESW_PORT_LAN4=0

**Comment by gushengyuan** [comment]
手头有多余的HC5761A， @hanwckf 需要的话可以赠送一只。

**Comment by hanwckf** [comment]
> 手头有多余的HC5761A， @hanwckf 需要的话可以赠送一只。

可以

**Comment by gushengyuan** [comment]
给个邮寄地址，我邮过来。
抱歉这些时间很少上来看邮件




| |
顾胜元@BJ
邮箱：gushengyuan2002@163.com
|

签名由 网易邮箱大师 定制

在2019年11月25日 13:10，hanwckf 写道：

手头有多余的HC5761A， @hanwckf 需要的话可以赠送一只。

可以

**Comment by hanwckf** [comment]
> 给个邮寄地址，我邮过来。 抱歉这些时间很少上来看邮件 | | 顾胜元@BJ 邮箱：gushengyuan2002@163.com | 签名由 网易邮箱大师 定制 在2019年11月25日 13:10，hanwckf 写道： 手头有多余的HC5761A， @hanwckf 需要的话可以赠送一只。 可以 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是发到gushengyuan2002@163.com这个邮箱么？

**Comment by gushengyuan** [comment]
对的




| |
顾胜元@BJ
邮箱：gushengyuan2002@163.com
|

签名由 网易邮箱大师 定制

在2019年12月18日 23:14，hanwckf 写道：

给个邮寄地址，我邮过来。 抱歉这些时间很少上来看邮件 | | 顾胜元@BJ 邮箱：gushengyuan2002@163.com | 签名由 网易邮箱大师 定制 在2019年11月25日 13:10，hanwckf 写道： 手头有多余的HC5761A， @hanwckf 需要的话可以赠送一只。 可以 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是发到gushengyuan2002@163.com这个邮箱么？

**Comment by hanwckf** [comment]
https://github.com/hanwckf/rt-n56u/commit/ceb2a1cea9bcc10858c4b6f3255ae079567f2ede
已经适配，但是SD卡不能工作。USB和所有LED可以正常工作。
