### ISSUE TITLE
请求加入弱信号剔除和弱信号拒连功能，很实用呢

### ISSUE THREAD

**Issue by qpzr** [hanwckf/rt-n56u#310]
RT

**Comment by chenxudong2020** [comment]
这个功能 我用过hiboy的固件发现 wifi连接速度会变慢

**Comment by qpzr** [comment]
> 这个功能 我用过hiboy的固件发现 wifi连接速度会变慢

你把限制值调到-70到-80之间就好 基本控制在一间房或者两堵墙里面 当然实际的极限距离 需要你拿手机装WIFI信号测试软件去跑几分钟得出平均值更准确
