### ISSUE TITLE
K2P&K2 EAP部分出现问题

### ISSUE THREAD

**Issue by georgeent** [hanwckf/rt-n56u#316]
更新，使用本站项目内最新下载的固件刷机后无法启动，但通过breed进去做了： 恢复出厂设置后就能正常使用了，该版本MD5如下
c7bac3b464485617fcb9f09e17671b4f  PSG1218.trx

其余的就等上游软件对WPA3-Enterprise的支持了. 我测试过WPA3 Personal (SAE)
在最新版本的IOS&Android 上已经支持WPA3-PSK了

**Comment by hanwckf** [comment]
WPA3看起啦是可以在最新的7615驱动里启用的，但是我手头现在还没有支持WPA3的客户端，以后有机会再调了
