### ISSUE TITLE
请添加CentOS下安装依赖包的说明，已写好范本

### ISSUE THREAD

**Issue by ye61123** [hanwckf/rt-n56u#318]
作为三大发行版之一，许多服务器均采用CentOS，但其包管理为yum而非apt，故认为有必要增加配置说明。本人使用CentOS8安装依赖后编译成功

CentOS7:
sudo yum update
sudo yum upgrade
sudo yum install ncurses-* flex byacc bison zlib-* texinfo gmp-* mpfr-* gettext libtool* libmpc-* gettext-* python-docutils nano help2man
sudo yum groupinstall "Development Tools"

CentOS8：
##CentOS8不能直接通过yum安装texinfo，help2man，python-docutils。请去官网下载发行的安装包编译安装
##以texinfo为例
#cd /usr/local/src
#sudo wget http://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.gz
#sudo tar zxvf texinfo-6.7.tar.gz
#cd texinfo-6.7
#sudo ./configure
#sudo make
#sudo make install

sudo yum update
sudo yum upgrade
sudo yum install ncurses-* flex byacc bison zlib-*  gmp-* mpfr-* gettext libtool* libmpc-* gettext-*  nano 
sudo yum groupinstall "Development Tools"

**Comment by yanziyuan** [comment]
CentOS7 编译失败
