### ISSUE TITLE
DIR-882 WPAHandshakeMsgRetryExec::Group rekey timeout from 

### ISSUE THREAD

**Issue by WatchKitty** [hanwckf/rt-n56u#319]
仅开启160Mhz频宽的5G频段，大概每天或每两天会出现此警告，每次踢下线的设备还是不一样的，踢下线后能重连，想问大佬是什么问题，之前有人提出类似issue美的冰箱的我仔细阅读了，但是我这边的设备都是智能手机或者笔记本被踢下线的，不知道是什么原因，可以提供设备给大佬检查

**Comment by WatchKitty** [comment]
又出现了新的报错 ICV Error
Apr 16 13:00:29 kernel: ICV Error, Addr1 = MAC1, Addr2 = MAC2
Apr 16 13:00:29 kernel: 	HTC/UC2ME/MC/BC=0/1/0/0, WlanIndex=1, SEC Mode=4
Apr 16 13:00:29 kernel: 	FCE Error(FC)=0, CM=0, CLM=0, I=1, T=0, LM=0
Apr 16 13:00:29 kernel: 	Fragment Frame(FRAG)=0

**Comment by xzp44** [comment]
我的也是，客户端是小米云台版摄像机，连的2g无线网，显示能路由器，但没有网络。

**Comment by WatchKitty** [comment]
感谢h大，是因为设备不支持mu-mimo，关闭mu-mimo后就不报错了
