### ISSUE TITLE
Problem with WPHY Mode

### ISSUE THREAD

**Issue by lyolic** [hanwckf/rt-n56u#322]
I have set "n only" option in "Wireless - General (2.4GHz)", but in "Wireless & Wired Info - Wireless (2.4GHz)" tab I see "WPHY Mode	: 11b/g".
I use latest release of NEWIFI3.trx firmware.

**Comment by hanwckf** [comment]
Please try the latest firmware.

**Comment by lyolic** [comment]
Now everything is OK with WPHY Mode
