### ISSUE TITLE
希望能搞个Github Actions自动编译

### ISSUE THREAD

**Issue by FreeGAV** [hanwckf/rt-n56u#326]
就像iljiamin那样可以利用Github Actions自动编译

**Comment by Tony-LYX** [comment]
chongshengb的yml文件自己复制一份，修改仓库地址和编译配置文件名称就可以了。chongshengb的仓库就是从hanwckf这里拉过去修改的，基本没区别。

**Comment by ywycd** [comment]
https://github.com/muziling/Padavan-build这个是别人修改的，源是hanwckf默认nano固件。
