### ISSUE TITLE
极路由4增强版刷Padava固件问题？

### ISSUE THREAD

**Issue by hfby** [hanwckf/rt-n56u#328]
极路由4增强版以前刷过Padava固件，成功进入系统；后来一直刷的是openwrt系统，现在就是openwrt系统，现在进breed怎么都不能刷Padava的固件，Padava固体能刷进去，极路由4重启红灯一直亮，就是不能进Padava，网络IPv4 默认网关:没有？刷以前刷成功的Padava版本，一样的没有网络IPv4 默认网关？怎么回事？谢谢大神指点一二！！！

**Comment by chenxudong2020** [comment]
先早breed恢复官方的备份系统 然后从新解开ssh 然后修改MAC 再次刷padavan试试

**Comment by hfby** [comment]
就是这样解决了，谢谢回答！
