### ISSUE TITLE
32M 7621固件重启问题

### ISSUE THREAD

**Issue by wozualong** [hanwckf/rt-n56u#329]
测试机型K2P 32M硬改，在不间断ping路由器观察连通状况的情况下，重启路由器仍有概率发生死机，只能断电重启，但是不去ping路由器的话，重启测试无问题

**Comment by omnjpa27516** [comment]
https://github.com/chongshengB/rt-n56u/commit/418a2b19b8f3041fd434186da6f89e7ccec7cfb8
https://github.com/chongshengB/rt-n56u/commit/c9b3af242ac2dec418df0ebcce6c757536173d64
@hanwckf
