### ISSUE TITLE
是否可以集成FRPC

### ISSUE THREAD

**Issue by simonchan6688** [hanwckf/rt-n56u#33]
是否可以集成FRPC

**Comment by hcym** [comment]
512M的v2ray不知道行不行？哈哈，贪婪

**Comment by hanwckf** [comment]
@hcym 在ss还能用的时候不会加v2ray……

**Comment by simonchan6688** [comment]
如果有已编译好的FRPC文件，请问如何集成到Rom中去？我尝试了在trunk/user/scripts加入frpc文件及在此文件夹下的Makefile内加入到romfs/bin的链接。编译后frpc文件只有1K大小。且无法使用

**Comment by hanwckf** [comment]
> 如果有已编译好的FRPC文件，请问如何集成到Rom中去？我尝试了在trunk/user/scripts加入frpc文件及在此文件夹下的Makefile内加入到romfs/bin的链接。编译后frpc文件只有1K大小。且无法使用

makefile按照这个来就可以了：
```makefile
SRC_NAME = frp16.1
THISDIR = $(shell pwd)

all:
	@echo "done"

clean:
	@echo "done"

romfs:
	$(ROMFSINST) -S $(THISDIR)/$(SRC_NAME)/frpc /usr/bin/frpc
```
然后修改`user/Makefile`，插入`dir_y += frp`

**Comment by simonchan6688** [comment]
is greeted! u r nice! thanks,

**Comment by simonchan6688** [comment]
> > 如果有已编译好的FRPC文件，请问如何集成到Rom中去？我尝试了在trunk/user/scripts加入frpc文件及在此文件夹下的Makefile内加入到romfs/bin的链接。编译后frpc文件只有1K大小。且无法使用
> 
> makefile按照这个来就可以了：
> 
> ```makefile
> SRC_NAME = frp16.1
> THISDIR = $(shell pwd)
> 
> all:
> 	@echo "done"
> 
> clean:
> 	@echo "done"
> 
> romfs:
> 	$(ROMFSINST) -S $(THISDIR)/$(SRC_NAME)/frpc /usr/bin/frpc
> ```
> 
> 然后修改`user/Makefile`，插入`dir_y += frp`

Is greeted! u r nice! thanks,

**Comment by simonchan6688** [comment]
老大，问自动脚本的写法。判断wan状态自动开启或关停frpc。如下，如何增加自动关停？
### $1 - WAN action (up/down)
### $2 - WAN interface name (e.g. eth3 or ppp0)
### $3 - WAN IPv4 address
if [ "up" = "$1" ] #接口启动，就是拨号成功
then
frp.sh &
fi
