### ISSUE TITLE
PING的丢包率多少合格？

### ISSUE THREAD

**Issue by Os-glthub** [hanwckf/rt-n56u#331]
<img width="642" alt="微信截图_20200420175928" src="https://user-images.githubusercontent.com/52124855/79743117-98029480-8336-11ea-8088-067f39fe65c1.png">

驱动5.0，王者偶尔460

**Comment by MeIsReallyBa** [comment]
这是2.4g？

**Comment by MeIsReallyBa** [comment]
我拿2.4g测了下，跑4000个没丢包。。。你换个信道试试v

**Comment by Os-glthub** [comment]
> 我拿2.4g测了下，跑4000个没丢包。。。你换个信道试试v

刚才跑了10W个包，信道自动。中途电脑出现了重连现象，路由器里没看到日记，无法判断是PC问题还是路由器。手机未关注。

<img width="379" alt="微信截图_20200421143120" src="https://user-images.githubusercontent.com/52124855/79832882-ed917c80-83dc-11ea-92f3-079d37af4d8e.png">
