### ISSUE TITLE
新版的固件web默认隐藏vpn页面 请问如何能显示出来？能加入openvpn吗？

### ISSUE THREAD

**Issue by kiho666** [hanwckf/rt-n56u#334]
新版的固件web默认隐藏vpn页面 请问如何能显示出来？能加入openvpn吗？

**Comment by kiho666** [comment]
型号360P2

**Comment by kiho666** [comment]
请问有openvpn吗？

**Comment by kiho666** [comment]
添加CONFIG_FIRMWARE_WEBUI_HIDE_VPN选项，可以隐藏webui中的vpn页面

**Comment by texchan** [comment]
openvpn在配置里要自己编译默认没有开启

![vpn](https://user-images.githubusercontent.com/37391247/80079353-c1affb80-8582-11ea-9ec4-9a35abe76337.jpg)
还有相关ui很好配的

**Comment by hanwckf** [comment]
https://github.com/hanwckf/rt-n56u/commit/a2b295895491a787cc35207a25d454fb987d3bd7

**Comment by chenbaker** [comment]
“更大设置”这里进去，VPN服务端和VPN客户端都是一片空白，什么原因呢？可以指点一下吗？带一下成长，谢谢！yml配置文件里已经设置 echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=y" >> .config 是设置不对，还是另有开关，用的是云编译
