### ISSUE TITLE
报告事项，关于1个小问题和2项软件的请求

### ISSUE THREAD

**Issue by mida2011** [hanwckf/rt-n56u#347]
很多开发者都集成的是您的固件代码，因此bug一致：

在4.1.2无线驱动4月27日最源码编译的固件，“无线交换机（AP）”模式下：
  1、系统管理--->工作模式--->无线交换机（AP） ；
  2、“AP-client+AP”这个桥接模式无法连接；
telnet客户端是常用软件，麻烦您集成，同时请集成特种vpn和vlan合集软件softether。谢谢了

**Comment by mida2011** [comment]
softether 支持l2tp sstp服务器，还支持tcp任意端口 icmp dns协议hub桥接 vlan网络。可谓一软多能。

**Comment by mida2011** [comment]
加入了telnet，不错.
再加入softether会让无线路由变身成真正的路由的.

**Comment by hanson-l** [comment]
softether不是有了吗，自己改config编一版吧

**Comment by mida2011** [comment]
有没有靠谱教程，推荐一个，或指点一下。谢谢

**Comment by mida2011** [comment]
yml文件修改一个了，新建一个Releases,没做过，烦请指点。

和以前linux上编译不一样，修改代码，make。。。。打扰了

**Comment by mida2011** [comment]
Releases建成了。不知道用chongb的yml可否，这个没试过。。。正在编译

**Comment by mida2011** [comment]
哦，好像应该用你的.travis.yml

**Comment by mida2011** [comment]
直接用.travis.yml生成config吗？

**Comment by mida2011** [comment]
麻烦给一个.github/workflows/build.yml？ 俺fork一个试试
