### ISSUE TITLE
RM2100升级校验错误

### ISSUE THREAD

**Issue by 0x5826** [hanwckf/rt-n56u#352]
Apr 29 22:13:16 httpd[392]: Firmware update: Incorrect image ProductID: RM2100! Expected is Redmi-AC2100.

**Comment by 0x5826** [comment]
1.重命名boards目录为Redmi-AC2100
2.修改RM2100配置模板的ProductID为Redmi-AC2100
后重新编译升级成功，建议都以Redmi-AC2100或者以RM2100为标识吧

**Comment by hanwckf** [comment]
`mtd_write -r write /tmp/RM2100.trx Firmware_Stub`
