### ISSUE TITLE
Noisy log with  errors

### ISSUE THREAD

**Issue by lyolic** [hanwckf/rt-n56u#353]
Hi,
in the latest release I receive many error in log

> Apr 28 15:51:57 kernel: pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
> Apr 28 15:51:57 kernel: pci 0000:00:00.0: BAR 0: can't assign mem (size 0x80000000)
> Apr 28 15:51:57 kernel: pci 0000:00:01.0: BAR 0: can't assign mem (size 0x80000000)
> .......
> Apr 28 15:51:57 kernel: MT7603 AP Driver version 4.1.2.0_20190222
> Apr 28 15:51:57 kernel: mt7603_init()-->
> Apr 28 15:51:57 kernel: mt_bcn_buf_init(224): Not support for HIF_MT yet!
> Apr 28 15:51:57 kernel: <--mt7603_init()
> ......
> Apr 28 15:51:57 kernel: l1set_profile_path() profile remain /etc/Wireless/RT2860/RT2860AP.dat
> ....
> 
> Apr 28 15:51:59 kernel: wmode_band_equal(): Band Equal!
> Apr 28 15:51:59 kernel: Key1Str is Invalid key length(0) or Type(0)
> Apr 28 15:51:59 kernel: Key2Str is Invalid key length(0) or Type(0)
> Apr 28 15:51:59 kernel: Key3Str is Invalid key length(0) or Type(0)
> Apr 28 15:51:59 kernel: Key4Str is Invalid key length(0) or Type(0)
> .....
> Apr 28 15:52:00 kernel: NICInitPwrPinCfg(14): Not support for HIF_MT yet!
> Apr 28 15:52:00 kernel: NICInitializeAsic(588): Not support rtmp_mac_sys_reset () for HIF_MT yet!
> .....
> Apr 28 15:52:09 kernel: AsicSetRalinkBurstMode(4325): Not support for HIF_MT yet!
> Apr 28 15:52:09 kernel: RTMPSetPiggyBack(943): Not support for HIF_MT yet!
> Apr 28 15:52:09 kernel: AsicSetTxPreamble(4312): Not support for HIF_MT yet!

Is it normal?
I use newifi3.trx

**Comment by hanwckf** [comment]
It's just normal.
