### ISSUE TITLE
Building firmware - can't find file to patch at input line 31573 on Samba

### ISSUE THREAD

**Issue by spamsool** [hanwckf/rt-n56u#360]
Hi,
I tried to build a new image for NEWIFI3 today and I get the following issue in the building process:
Would you please have a look on this? Thanks! ;)

patching file source3/smbd/smb2_signing.c
can't find file to patch at input line 31573
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- vfs_default.c      2015-02-22 22:11:32.000000000 +0800
|+++ vfs_default-avm.c  2020-05-01 00:31:41.659641000 +0800
--------------------------
File to patch:

I press [Enter]
Skip this patch? [y]

**Comment by hanwckf** [comment]
fixed in https://github.com/hanwckf/rt-n56u/commit/17aa068cebcb331abc94d50b39d76f4a5e130187
