### ISSUE TITLE
 c67db94测试日志看到如下错误，请教

### ISSUE THREAD

**Issue by diaoz** [hanwckf/rt-n56u#38]
CmdExtStaRecUpdateRsp::ERROR::EventExtCmdResult.u4Status = 0x10003

Replay Counter Different in pairwise msg 2 of 4-way handshake!

**Comment by diaoz** [comment]
k2p_nano

**Comment by hcym** [comment]
我编译的是32／512的，只保留ssr，去掉usb等等等等，没看到什么不正常，感觉不错

**Comment by hanwckf** [comment]
@diaoz 这个是mt7615驱动的日志输出，具体啥意思我也不知道，但是已知在openwrt 18.06(4.14内核)以及PandoraBox固件里不会出现，也不会导致什么异常情况。

**Comment by diaoz** [comment]
@hanwckf 明白了，非常感谢~

**Comment by LIGA0301** [comment]
> @diaoz第二行那个是有错误wifi密码的客户端尝试连接

好像不是这个原因唉大佬，我也遇到了，7621编译的这三个型号都有这个问题（B70，R4A，NEWIFI3）
每个小时准时出现一次
![日志](https://github.com/hanwckf/rt-n56u/assets/133008074/6bd8502f-fa8b-46ea-8379-4460f3361a48)
