### ISSUE TITLE
自动编译麻烦添加RE6500

### ISSUE THREAD

**Issue by ihuaer** [hanwckf/rt-n56u#380]
今天看了群主自动编译的固件，发现固件少了RE6500。麻烦楼主添加一个自动编译。

我尝试着自动编译，不过编译好后，安装无法启动，可能哪里编译有问题。

**Comment by SuzukiHonoka** [comment]
每个人都是你的保姆？

**Comment by LimonChoms** [comment]
> 每个人都是你的保姆？

总会有理直气壮的伸手党

**Comment by ihuaer** [comment]
done
