### ISSUE TITLE
config for Totolink A7000R?

### ISSUE THREAD

**Issue by rusnazip** [hanwckf/rt-n56u#391]
Hi. Could you help me make a config for totolink a7000r ? I tried to build it myself using the config from dir-882 as an example but it doesn't start, the console freezes on loading

boot log

LINUX started...
Linux version 3.4.113 (padavan@hms) (gcc version 7.4.0 (crosstool-NG UNKNOWN) ) #1 SMP Tue May 19 14:07:14 +09 2020

MediaTek SoC: MT7621A, RevID: 0103, RAM: DDR3, XTAL: 40MHz
CPU/OCP/SYS frequency: 880/293/220 MHz
prom memory:128MB
CPU revision is: 0001992f (MIPS 1004Kc)
Determined physical RAM map:
 memory: 08000000 @ 00000000 (usable)
Zone PFN ranges:
  Normal   0x00000000 -> 0x00008000
Movable zone start PFN for each node
Early memory PFN ranges
    0: 0x00000000 -> 0x00008000
Detected 3 available secondary CPU(s)
Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
PERCPU: Embedded 7 pages/cpu @81103000 s5952 r8192 d14528 u32768
Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 32512
Kernel command line: console=ttyS0,57600n8 root=/dev/mtdblock4 rootfstype=squashfs
PID hash table entries: 512 (order: -1, 2048 bytes)
Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
Writing ErrCtl register=00072e0b
Readback ErrCtl register=00072e0b
Memory: 126056k/131072k available (2872k kernel code, 5016k reserved, 551k data, 220k init, 0k highmem)
Hierarchical RCU implementation.
NR_IRQS:72
MIPS GIC RevID: 3.0
Setting up vectored interrupts
console [ttyS0] enabled
Calibrating delay loop... 577.53 BogoMIPS (lpj=1155072)
pid_max: default: 32768 minimum: 301
Mount-cache hash table entries: 512
Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
CPU revision is: 0001992f (MIPS 1004Kc)
Synchronize counters for CPU 1: done.
Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
CPU revision is: 0001992f (MIPS 1004Kc)
Synchronize counters for CPU 2: done.
Primary instruction cache 32kB, VIPT, 4-way, linesize 32 bytes.
Primary data cache 32kB, 4-way, PIPT, no aliases, linesize 32 bytes
MIPS secondary cache 256kB, 8-way, linesize 32 bytes.
CPU revision is: 0001992f (MIPS 1004Kc)
Synchronize counters for CPU 3: done.
Brought up 4 CPUs
NET: Registered protocol family 16
▒▒

Where can there be a problem in the settings?

**Comment by nicefile** [comment]
@rusnazip I assume You should disable all gpio under board.h unless You are 100% sure GPIO configuration of A7000R . Leds are also not needed "for now". Except missing external PA/LNA this look promising . Also mind user chongshengB share more recent driver version 5.0.4 . I'm using it atm on my custom build

**Comment by rusnazip** [comment]
@nicefile Hi. Thanks for the answer. Just today I managed to build a working firmware. I disabled gpio as you recommend. But I don't understand find out the gpio number for led and btn? Is there an instruction?

**Comment by rusnazip** [comment]
@nicefile And how do I use the version 5 wifi driver? I'm currently using 4.4.2.1

**Comment by nicefile** [comment]
@rusnazip sudo ./build_firmware_modify DIR-878-5.0 for my router. I've imported proprietary/rt_wifi/rtpci/5.0.4.0 from chongshengB and added few new config options (will ask for them while compilation anyway)
Also gpio have no userland access from padavan afaik
1st maybe source code anywhere ? or firmware investigation
2nd enabling debug kernel options for GPIO . gpio has to be seen in /sys/class/gpio
3nd option is to trail and error using most common gpio numbers in build config .

**Comment by rusnazip** [comment]
@nicefile Thank you for the clarification. How do I activate debug option for GPIO in kernel ? thanks

**Comment by nicefile** [comment]
@rusnazip Totolink A7000R is openwrt supported  from commit 3f68cffd276df5b164ea0c7ecafb8fa062aa7a41 so we have gpio configuration ready :
+                       label = "reset";
+                       gpios = <&gpio0 4 GPIO_ACTIVE_LOW>;

+               led_sys: sys {
+                       label = "a7000r:blue:sys";
+                       gpios = <&gpio0 18 GPIO_ACTIVE_LOW>;

I just forgot to check openwrt ... sorry

**Comment by rusnazip** [comment]
@nicefile Thank you very much for the information. I'll try =)
