### ISSUE TITLE
请教各位在padavan的wifi上单独禁用IPV6的思路

### ISSUE THREAD

**Issue by llpub** [hanwckf/rt-n56u#395]
自从启用了移动的残废IPV6，一些支持IPV6的国外网站比在纯IPV4环境下体验差太多，甚至手机上看b站都开始卡了。不过由于台式机(插网线)上要调试一些东西，台式机上有IPV6总比没有强。
想着在wifi上单独禁用IPV6，给手机保留一片IPV4的净土。
求指点一下思路，虽然通过图形界面是不太可能，但在后台终端应该还有点希望。

**Comment by 289699522** [comment]
LAN DHCPv6 服务器设置为stateful，android手机就获取不到v6地址了

**Comment by llpub** [comment]
@289699522 谢谢，这样确实可以。
对IPv6的stateful/stateless不太理解，方便的话望再给稍微提示一下其中原理：DHCPv6的stateful为何能区别WiFi和有线网络？据我观察WiFi和有线都是同一个IPv4网段。
