### ISSUE TITLE
K2 1218 AP模式下弱信号剔除失效！

### ISSUE THREAD

**Issue by mcucore** [hanwckf/rt-n56u#404]
MAC (AP Main)	: FC:7C:02:69:D9:A4
Operation Mode	: AP
WPHY Mode	: 11g/n
Channel Main	: 13

AP Main Stations List
----------------------------------------
MAC                PhyMode  BW MCS SGI LDPC STBC TRate RSSI PSM Connect Time
D4:61:9D:5E:55:C6  HTMIX   20M  15  NO   NO   NO  130M  -47 YES 00:17:43
58:85:E9:F3:5F:63  HTMIX   20M   4  NO   NO  YES   39M  -79 YES 00:26:18
64:B0:A6:19:96:B0  HTMIX   20M  15  NO   NO   NO  130M  -38 YES 00:20:33
00:0A:F5:F3:DA:FC  HTMIX   20M   7  NO   NO  YES   65M  -66 YES 00:15:48

**Comment by mcucore** [comment]
补充，5G的弱信号剔除是好的，2.4G无效，到阀值不会剔除。

**Comment by mcucore** [comment]
补充，经测试，net_wifi.c 中的代码应该没啥问题，正确执行了iwpriv ra0 set KickStaRssiLow=-65等命令，问题应该在附带的2.4G驱动不支持弱信号剔除功能。有啥解决办法吗？

**Comment by ju0594** [comment]
> 补充，经测试，net_wifi.c 中的代码应该没啥问题，正确执行了iwpriv ra0 set KickStaRssiLow=-65等命令，问题应该在附带的2.4G驱动不支持弱信号剔除功能。有啥解决办法吗？

2.4G有两个驱动,2.7版本和3.0版本,2.7版本信号好但是不支持弱信号剔除,3.0支持弱信号剔除但是信号差点.

**Comment by mcucore** [comment]
用3.0.5.0 7620驱动，2.4G的弱信号剔除就正常了，感谢！
