### ISSUE TITLE
红米ac2100的2.4G应该是MT7603E_EPA_ELNA(外置功放)才对

### ISSUE THREAD

**Issue by ferhung-mtk** [hanwckf/rt-n56u#425]
看拆机，红米ac2100的2.4G应该是MT7603E_EPA_ELNA(外置功放)才对，但是在泄露的驱动里面暂时没有看到相关定义

**Comment by MeIsReallyBa** [comment]
这个是读取eeprom的，驱动不会影响。

**Comment by ferhung-mtk** [comment]
> 这个是读取eeprom的，驱动不会影响。

 这个决定了eeprom的是以内或外置的方式进行bin的保存，然后才开始读取，搞不清楚去掉以后仍然有效
