### ISSUE TITLE
是否可以集成v2ray

### ISSUE THREAD

**Issue by chaohua27** [hanwckf/rt-n56u#44]
大佬，是否可以集成v2ray？虽v2的体积和耗资源跟$$没法比，但v2的速度和稳定性比$$强太多。希望能将v2做成可选项，非常感谢！

**Comment by chaohua27** [comment]
若体积太大，貌似可以用upx进行压缩，也可精简组件，可参考如下两贴：
https://gobomb.github.io/post/cross-complie-v2ray/
https://steemit.com/cn/@v2ray/meemg-v2ray

**Comment by hcym** [comment]
mtk的感觉不行，arm的不错，pc上面表现最好，基本首选

**Comment by ntgeralt** [comment]
虽然mtk不大行，但速度还可以，且伪装为大势所趋。

**Comment by Os-glthub** [comment]
H大你好，用你分享的K2P固件安逸，还在维护 Padavan的就两个H大了，每次分享新版本都想体验一番。我是个普通用户提个需求，在原有固件的基础上做一个v2ray插件包，把SS/v2ray分出来，按需求自己选装。听说k2p内存不够，如果把梯子平台分开是否可行？

**Comment by hanwckf** [comment]
> H大你好，用你分享的K2P固件安逸，还在维护 Padavan的就两个H大了，每次分享新版本都想体验一番。我是个普通用户提个需求，在原有固件的基础上做一个v2ray插件包，把SS/v2ray分出来，按需求自己选装。听说k2p内存不够，如果把梯子平台分开是否可行？

老毛子固件不太适合做这种方式，还是从源码里面集成比较好。
暑假有空的话会弄个v2ray进去..

**Comment by ntgeralt** [comment]
@hanwckf 我看了你的ss启动脚本，真是非常精致，也觉得你做这个完全不是难事，换一下启动就行了。你说的麻烦可能只有打造操作界面

**Comment by Os-glthub** [comment]
> > H大你好，用你分享的K2P固件安逸，还在维护Padavan的就两个H大了，每次分享新版本都想体验一番。我是个普通用户提个需求，在原有固件的基础上做一个v2ray插件包，把SS / v2ray分出来，按需求自己选装。听说K2P内存不够，如果把梯子平台分开是否可行？
> 
> 老毛子固件不太适合做这种方式，还是从源码里面集成比较好。
> 暑假有空的话会弄个v2ray进去..

感谢，期待大佬作品。辛苦了

**Comment by banricho** [comment]
支持。
不过我认为 vmess 协议对比 shadowsocks 协议并没有优势，两者的稳定性、安全性实际上是差不多的。
v2ray 作为一个平台的优势非常明显，拥有非常强大的分流能力，并且可以同时作为客户端和服务端。
有了 v2ray 之后，无论是作为透明代理还是内网穿透都非常方便，一个 JSON 就可以搞定了……

**Comment by twedu** [comment]
能不能去掉那个学校的拨号客户端，带上v2ray

**Comment by ChinaNuke** [comment]
已经十月了，期待加入v2ray。非常喜欢这个固件，但v2ray是刚需

**Comment by hcym** [comment]
跑的很吃力

**Comment by hanwckf** [comment]
以后会考虑trojan，不会集成大体积的golang程序
