### ISSUE TITLE
ss及ssr极容易被墙，trojan与v2ray这么好用，为何大佬固件仍采用ss与ssr这种容易被封的？

### ISSUE THREAD

**Issue by gimgoo** [hanwckf/rt-n56u#441]
ss及ssr极容易被墙，事实证明trojan与v2ray这么好用，哪怕敏感时期仍然稳的一匹，为何大佬固件仍采用ss与ssr这种容易被封的？

**Comment by AlphaAnother** [comment]
中转机场无惧被封 大部分人没那闲工夫自己建 何况每月花点小钱就能上百个个节点正常使用 自己折腾那几个小节点图啥呢
另外 V2这东西UDP残废 几年的恶性bug最近才修 真要吹这玩意？

**Comment by limobai2333** [comment]
占用资源低这就是一大优点，精简。不容易出问题。稳定为王道。

**Comment by j19981106** [comment]
> ss及ssr极容易被墙，事实证明trojan与v2ray这么好用，哪怕敏感时期仍然稳的一匹，为何大佬固件仍采用ss与ssr这种容易被封的？

容易被封那大概率是因为那个IP段机场泛滥，实际上SS/SSR本身并不会被识别到。
