### ISSUE TITLE
请求适配Netgear R6220

### ISSUE THREAD

**Issue by lwzheng12138** [hanwckf/rt-n56u#46]
方案是7621+7603+7612

128M ram+128M NAND flash

复位键 GPIO#14，WPS 键 GPIO#7，RFKILL 键 GPIO#8

一个USB 2.0

4千兆LAN+1千兆WAN

**Comment by hanwckf** [comment]
网件的机器要做分区表自适应识别比较麻烦，再说手头也没有R6220，所以暂时不会适配
