### ISSUE TITLE
怎么从源码中把vpn服务器和客户端删除

### ISSUE THREAD

**Issue by 1164715233** [hanwckf/rt-n56u#460]
如题，用“CONFIG_FIRMWARE_INCLUDE_*****” sed -i '/匹配字符串/d' 删除可以吗？

**Comment by FreeGAV** [comment]
用这个自编译   跟chongshengB自编译一样可以自己配置需要的插件
https://github.com/Chensungw/Padavan-build

**Comment by 1164715233** [comment]
> 用这个自编译 跟chongshengB自编译一样可以自己配置需要的插件
> https://github.com/Chensungw/Padavan-build

请问能告诉我主界面vpn服务器和客户端的插件代码是什么吗？
