### ISSUE TITLE
文件名有冒号(:)，git clone代码失败

### ISSUE THREAD

**Issue by m4wayne** [hanwckf/rt-n56u#476]
Resolving deltas: 100% (7838/7838), done.
error: invalid path 'trunk/user/ipset/ipset-6.x/tests/bitmap:ip.t'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

这是ubuntu下git clone报错的信息。
windows下文件名不能有冒号，拉取代码失败就算了，这ubuntu下也会失败。
大家遇到的没有，怎么解决的
谢谢

**Comment by avatasia** [comment]
# 忽略路径中的转义字符

git config --global core.protectNTFS false

# 禁用换行符转换

git config --global core.autocrlf false

# 中文文件名，乱码问题。设为false的话，就不会对0x80以上的字符进行quot

git config --global core.quotepath false
