### ISSUE TITLE
SS配置问题

### ISSUE THREAD

**Issue by xiangtailiang** [hanwckf/rt-n56u#49]
设备：K2P
固件版本：最新的DRV固件。

SS设置：
SS设置好服务器连接，并到"dnsmasq设置"，去掉gxxlist配置前的"#"注释符，保存设置。
然后开启dns-forwarder，并设置好转发的ip和端口。

结果：
Google的页面可以访问，YouTube能访问，但视频一直loading。
Facebook的页面会提示链接不安全，看描述是https的证书匹配到了其他域名，不是Facebook的域名。

猜测是DNS被污染了，但不知道如何解决？
我用Hiboy的固件，SS正常。

我很喜欢你这个简洁的固件，但唯独SS不正常，恳请提供一下解决思路，谢谢。

**Comment by hanwckf** [comment]
把ss页面的"高级设置"，dns-forwarder和dnsmasq.conf配置截图上来看看？

**Comment by simonchan6688** [comment]
同样是FaceBook访问不正常！
但是google和youtube都是正常的。
Chrome中proxy检查为*fbcdn.net加载失败。
用其他固件无此现象

**Comment by xiangtailiang** [comment]
我在使用这个固件fan qiang的时候遇到两个问题：
1、选用chnroute模式，很多网站都上不了，估计是dns解析不成功，我用的是ISP拨号自带的dns，没有单独设置。
2、后来改为gfw模式，发现部分网站能打开，部分不能。
现在直接安装了其它人提供的一键安装脚本，重新安装ssr，正常了。

wget -q http://dwz.cn/ssr-padavan-6 -O - | tar -xjvf - -C /etc && mtd_storage.sh save
nvram set crond_enable=1 && nvram commit

**Comment by hanwckf** [comment]
> 同样是FaceBook访问不正常！
> 但是google和youtube都是正常的。
> Chrome中proxy检查为*fbcdn.net加载失败。
> 用其他固件无此现象.
> 貌似如此设置后正常----
> 在‘高级设置’打开
> 启用自身代理 | 是
> 启用UDP代理 | 是
> 启用ss-tunnel | 是
> 本地端口:5353
> lan>dhcp设置>“dnsmasq设置”，去掉conf-dir=/etc/storage/gfwlist前的“＃”注释符

推荐使用dns-forwarder做DNS代理，因为UDP出国很不稳定
