### ISSUE TITLE
能否集成ngrok-c

### ISSUE THREAD

**Issue by zhaibin18** [hanwckf/rt-n56u#51]
多谢！
https://github.com/dosgo/ngrok-c

**Comment by ntgeralt** [comment]
你需要这些可以用hiboy。那个是重兵器。我感觉这里走轻新路线就好了。

**Comment by hanwckf** [comment]
建议用frp

**Comment by zhaibin18** [comment]
frp我查到都是go开发的，静态编译到mips平台都很大，C语言平台的只有https://github.com/KunTengRom/xfrp，这个最大的问题是不能短线重连，并且貌似已经没人维护了。

**Comment by CODEXP777** [comment]
hiboy 有编译好的frp，复制内内部存储或者u 盘，然后加配置文件，具体恩山有帖子，很简单。

**Comment by zhaibin18** [comment]
我自己编译了一个，放在K2、K2P里用没问题，https://github.com/zhaibin18/mipsel_tools/raw/master/ngrokc_k2_padavan
