### ISSUE TITLE
K2P这些日志能去除吗?

### ISSUE THREAD

**Issue by TurBoTse** [hanwckf/rt-n56u#521]
Dec  7 12:29:46 NTP Client: Synchronizing time to cn.pool.ntp.org.
Dec  7 12:29:48 NTP Client: System time changed, offset: -0.002720s
Dec  7 13:26:02 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 14:26:04 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 15:26:06 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 16:26:08 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 17:26:10 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 18:26:12 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 19:26:15 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 20:26:17 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 21:26:19 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 22:26:21 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  7 23:26:23 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 00:26:25 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 01:26:27 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 02:26:29 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 03:26:31 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 04:26:33 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 05:26:35 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 06:26:37 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 07:26:39 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 08:26:41 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 09:26:43 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 10:26:45 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 11:26:47 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 12:26:49 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 12:29:46 NTP Client: Synchronizing time to ntp1.aliyun.com.
Dec  8 12:29:48 NTP Client: System time changed, offset: -0.135460s
Dec  8 13:26:51 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 14:26:53 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 15:26:56 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 16:26:58 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 17:27:00 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 18:27:02 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 18:27:02 kernel: BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
Dec  8 19:27:04 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 20:27:06 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 21:27:08 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 22:27:10 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  8 23:27:12 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 00:27:14 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 00:27:14 kernel: BC, check_rx_pkt_pn_allowed (1)(0) Reject: come-in the 0 and now is 0
Dec  9 01:27:16 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 02:27:18 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 03:27:20 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 04:27:22 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 05:27:24 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 06:27:26 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 07:27:28 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 08:27:30 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 09:27:32 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 10:27:34 kernel: oooWPAParseEapolKeyData : the Group install  (1)
Dec  9 11:27:37 kernel: oooWPAParseEapolKeyData : the Group install  (1)

**Comment by 9dark9** [comment]
我也是这样，5g桥接的，有没有大神来说明下，要怎么处理？或者无视？

**Comment by 9dark9** [comment]
总算搞清楚了，这个是网络密钥轮换间隔引起的的日志

**Comment by godmodeon29** [comment]
> 7 декабря 12:29:46 NTP-клиент: синхронизация времени с cn.pool.ntp.org.
> 7 декабря 12:29:48 Клиент NTP: системное время изменено, смещение: -0.002720 с
> 7 декабря 13:26:02 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 14:26:04 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 15:26:06 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 16:26:08 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 17:26:10 ядро: oooWPAParseEapolKeyData: группа install (1)
> 7 декабря 18:26:12 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 19:26:15 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 20:26:17 ядро: oooWPAParseEapolKeyData: Групповая установка (1)
> 7 декабря 21:26:19 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 22:26:21 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 7 декабря 23:26:23 ядро: oooWPAParseEapolKeyData: установка группы (1 )
> 8 декабря 00:26:25 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 01:26:27 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 02:26:29 ядро: oooWPAParseEapolKeyData: установка группы ( 1)
> 8 декабря 03:26:31 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 04:26:33 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 05:26:35 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 06:26:37 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 07:26:39 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 08:26:41 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 09:26:43 ядро: oooWPAParseEapolKeyData: установка группы (1 )
> 8 декабря 10:26:45 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 11:26:47 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 12:26:49 ядро: oooWPAParseEapolKeyData: установка группы ( 1)
> 8 декабря 12:29:46 NTP-клиент: синхронизация времени с ntp1.aliyun.com.
> 8 декабря 12:29:48 Клиент NTP: системное время изменено, смещение: -0,135460 с
> 8 декабря 13:26:51 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 14:26:53 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 15:26:56 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 16:26:58 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 17:27:00 ядро: oooWPAParseEapolKeyData: установка группы (1 )
> 8 декабря 18:27:02 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 18:27:02 ядро: BC, check_rx_pkt_pn_allowed (1) (0) Отклонение: введите 0 и теперь 0
> 8 декабря 19 : 27: 04 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 20:27:06 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 21:27:08 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 22:27:10 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 8 декабря 23:27:12 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 00:27:14 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 00:27:14 ядро: BC, check_rx_pkt_pn_allowed (1) ( 0) Отклонить:
> введите 0 и теперь 0 9 декабря 01:27:16 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 02:27:18 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 03 : 27: 20 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 04:27:22 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 05:27:24 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 06:27:26 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 07:27:28 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 08:27:30 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 09:27:32 ядро: oooWPAParseEapolKeyData: установка группы (1 )
> 9 декабря 10:27:34 ядро: oooWPAParseEapolKeyData: установка группы (1)
> 9 декабря 11:27:37 ядро: oooWPAParseEapolKeyData: установка группы (1)

大家好，告诉我这个日志是什么意思?
