### ISSUE TITLE
能否合并ZTE_E8820S

### ISSUE THREAD

**Issue by liuyunwuhen** [hanwckf/rt-n56u#525]
能否合并ZTE_E8820S
https://github.com/liuyunwuhen/Padavan-build/tree/master/trunk/configs

**Comment by AlphaAnother** [comment]
Fork commit 再发个PR啊···

**Comment by liuyunwuhen** [comment]
已经提交

**Comment by liuyunwuhen** [comment]
> Fork commit 再发个PR啊···
已经提交

**Comment by AlphaAnother** [comment]
···你fork这个库 在你fork的rt-n56u这个库里把你的8820S配置加进去 再提交PR请求啊

**Comment by liuyunwuhen** [comment]
> ···你fork这个库 在你fork的rt-n56u这个库里把你的8820S配置加进去 再提交PR请求啊
我事小白 没有在github提交过PR 昨天少了1步 https://github.com/hanwckf/rt-n56u/pull/551
