### ISSUE TITLE
根据最新源码编译的PSG1218固件无法引导启动。

### ISSUE THREAD

**Issue by Yh793** [hanwckf/rt-n56u#532]
H大你好，使用https://github.com/hanwckf/rt-n56u/commit/58d066a87c4aa2a14644760ac2f40f513f155a49
源码编译的固件刷入后无法启动。刷入后只亮红灯，网口、WIFI都没反应。只编译了PSG1218。使用https://github.com/hanwckf/rt-n56u/commit/fbc4d41e91a7b33a98f372f65fccdbfe5bfd2301
源码编译的固件是正常的。

**Comment by Yh793** [comment]
https://github.com/hanwckf/rt-n56u/commit/0db9b27c8a1ef30e1e965da15d245d587c3a9d18 正常。
https://github.com/hanwckf/rt-n56u/commit/32fe988ee07ac3095b84c467a559fa8663e36578 这版出现问题。

**Comment by Yh793** [comment]
K2P刷入https://github.com/hanwckf/rt-n56u/commit/58d066a87c4aa2a14644760ac2f40f513f155a49正常启动。

**Comment by TurBoTse** [comment]
还以为是我的有问题，原来都是这样

**Comment by Yh793** [comment]
https://github.com/hanwckf/rt-n56u/commit/de7f5deb266e7591996bef04ab4ecf6e51a0e338 已修复。

**Comment by zhouzhenqi** [comment]
使用最新的8adef7b源码编译的PSG1218刷入后也是这个现象，只亮红灯，网口、WIFI都没反应。
