### ISSUE TITLE
System time in system log

### ISSUE THREAD

**Issue by minax007** [hanwckf/rt-n56u#536]
Dear all, 

the system time in the system log is not equal to the system time, which the router gets from the NTP settings. 

Whenever I start the router the system log shows January 1st and 00:00:00.

And this does not get updated later on. 

Jan  1 00:00:33 
Jan  1 00:00:34
and so on ....

**Comment by zouyonghao** [comment]
Time is right for me.

Do you see some logs about `NTP Client: Synchronizing time ....` ?

**Comment by minax007** [comment]
Dear @zouyonghao 
I am glad to see you replying to the issue I had posted :-)
Yes, I see those logs:

Jan  2 02:35:39 NTP Client: Synchronizing time to server2.de.pool.ntp.org.

But it doesn't synchronize the system time of the router.

**Comment by zouyonghao** [comment]
> Dear @zouyonghao
> I am glad to see you replying to the issue I had posted :-)
> Yes, I see those logs:
> 
> Jan 2 02:35:39 NTP Client: Synchronizing time to server2.de.pool.ntp.org.
> 
> But it doesn't synchronize the system time of the router.

I mean something like this `NTP Client: System time changed, offset: 2.046561s`

**Comment by minax007** [comment]
No I do not get this message.

**Comment by zouyonghao** [comment]
Then that is the problem... try another NTP server?

**Comment by minax007** [comment]
This sounds reasonable. 
Ok, I will give a try :-)

**Comment by minax007** [comment]
Wow! 
Now it works. 
Jan  1 16:13:57 NTP Client: System time changed, offset: 189349226.626505s

That was so simple that I couldn't figure out, that it was related to the NTP server. 
I was using those NTP-servers for a very long time ... and they were fine. 
But it seems that those are not working with Padvan ... strange. 
Anyway, thanks for your help!

**Comment by minax007** [comment]
The strange thing is that in the "Network Traffic" diagrams the former NTP-server data were shown correctly (time was always correct). 
Only in the system logs it was wrong. 
But now with the other NTP server, both work fine.
