### ISSUE TITLE
"www: 手机/平板模式v3 (#542)"这个怎么彻底删除啊？

### ISSUE THREAD

**Issue by itfish92** [hanwckf/rt-n56u#566]
我看这个提交已经被hanwckf大佬revert了，我编译出来后手机登陆还是有这个模式，好多图形都重叠的太乱了，
没办法我又git clone了完整代码 git checkout到几天前的代码，编译出来依旧有这个平板模式。。
提交平板模式这个代码这真太蛋疼了，hanwckf大佬的代码本就是走简洁模式的，非得整这么一出

**Comment by vb1980** [comment]
浏览器缓存清除一下

**Comment by TurBoTse** [comment]
> 浏览器缓存清除一下

你完善的不提交了？
