### ISSUE TITLE
K2P_nano-5.0+frp_0.20.0编译之后，外网怎么不用输密码就直接连上了（大哭）

### ISSUE THREAD

**Issue by xiaolong-chen** [hanwckf/rt-n56u#574]
背景：K2P，没有改过硬件，一直想装FRPC，把路由器映射到外网上，然后就可以远程管理路由器了
        折腾了一下午，K2P的内存有点小，所以选择了精简版（K2P_nano-5.0）为基础，然后找了比较小的FRPC（frp_0.20.0）版本，编译成功，刷入成功，自启脚本也给弄好了，然后尝试外网连接

FRPC配置
local_ip = 127.0.0.1
local_port = 80
remote_port = 20080

然后外网访问的时候【x.x.x.x:20080】，突然发现，不用输密码，直接就进管理页了
反而内网【192.168.2.1】访问的时候，还需要登陆输入密码。。。

编译改动
K2P_nano-5.0配置文件开启FRPC
FRPC的配置文件调整版本为0.20.0

**Comment by Ljzkirito** [comment]
FRPC配置
local_ip = 192.168.2.1
local_port = 80
remote_port = 20080

如果设置为127.0.0.1相当于自己访问自已，当然不需要密码，local_ip应为192.168.x.1这样的地址

**Comment by xiaolong-chen** [comment]
> FRPC配置
> local_ip = 192.168.2.1
> local_port = 80
> remote_port = 20080
> 
> 如果设置为127.0.0.1相当于自己访问自已，当然不需要密码，local_ip应为192.168.x.1这样的地址

嗯嗯，这样设置就好了，非常感谢
