### ISSUE TITLE
建议：增加smartdns

### ISSUE THREAD

**Issue by ntgeralt** [hanwckf/rt-n56u#58]
我最近试用了下smartdns，发现非常好用。能从多个DNS返回最快响应速度的结果，望集成

**Comment by hanwckf** [comment]
smartdns如果开源的话会集成进来的

**Comment by ntgeralt** [comment]
你好，关于newifi3 5月份固件，我这里插入exfat4 U盘，固件一直没发现设备，换其他固件则能识别。
