### ISSUE TITLE
使用最新的8adef7b源码编译的PSG1218刷入后也是这个现象，只亮红灯，网口、WIFI都没反应。

### ISSUE THREAD

**Issue by zhouzhenqi** [hanwckf/rt-n56u#586]
使用最新的8adef7b源码编译的PSG1218刷入后也是这个现象，只亮红灯，网口、WIFI都没反应。

_Originally posted by @zhouzhenqi in https://github.com/hanwckf/rt-n56u/issues/532#issuecomment-776091147_

**Comment by Os-glthub** [comment]
[PSG1218_3.4.3.9-099.zip](https://github.com/hanwckf/rt-n56u/files/5955213/PSG1218_3.4.3.9-099.zip)

**Comment by Yh793** [comment]
哥，看了下你的编译日志。固件超大小了。

**Comment by zhouzhenqi** [comment]
确实是超大小了，感谢指导。
