### ISSUE TITLE
R2100固件 放弃了么 

### ISSUE THREAD

**Issue by e71828** [hanwckf/rt-n56u#593]
感谢大佬前辈的无私奉献！
我遇到了一点问题，在一款便宜的小米路由器 xiaomi AC2100上。
## R2100 的编译及使用体验问题
1. [releases](https://github.com/hanwckf/rt-n56u/releases/tag/v2020-11-27) 里面没有编译的固件`R2100.trx `；
2. https://github.com/hanwckf/rt-n56u/blob/597083b2972c2f79117692a767fa14e2385ec717/trunk/configs/templates/R2100.config#L110-L122 导致编译出来是英文的系统界面，而且没有中文；
3. 我编译出来的固件中插件、功能较少，ss没有订阅功能，透明代理，故障转移，模式切换规则更新等；

p.s. `hiboyhiboy`编译出来的固件功能、插件又太多，但又没有可以源码。

**Comment by Yh793** [comment]
1、你可以自行编译，自动编译只是编译了常见的型号。https://github.com/hanwckf/scut_padavan_build H大的编译脚本。https://github.com/chongshengB/Padavan-build chongshengB 大佬的编译脚本。
2、配置文件自己编译的时候可以随意调整。
3、要插件全一点的话用chongshengB大佬的仓库。h大的仓库是比较纯净的。
