### ISSUE TITLE
请求han大神增加红米ac2100（rm2100）的nano固件，只想要纯净版，从k2p开始就喜欢纯净版

### ISSUE THREAD

**Issue by lijin8275575** [hanwckf/rt-n56u#625]
就2100这cpu装ssr也没太大作用，稳定性也不好

**Comment by Ljzkirito** [comment]
你可以自己编译一个啊：）
我个人编译仅含有VLMCSD的RM2100固件
[Github Actions](https://github.com/Ljzkirito/Actions-Padavan_Redmi-AC2100)

**Comment by lijin8275575** [comment]
> 你可以自己编译一个啊：）
> 我个人编译仅含有VLMCSD的RM2100固件
> [Github Actions](https://github.com/Ljzkirito/Actions-Padavan_Redmi-AC2100)

谢谢大神分享，我试试
