### ISSUE TITLE
请教如何去除VPN服务端和客户端

### ISSUE THREAD

**Issue by kingyan** [hanwckf/rt-n56u#63]
CONFIG_FIRMWARE_INCLUDE_OPENVPN=n
CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n
CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n
CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n
都设置得 n ，用得PSG1218_nano.config配置文件编译，页面还是有VPN服务端和客户端这两个选项。

**Comment by hanwckf** [comment]
这个要改源码才能去除

**Comment by kingyan** [comment]
刷得您编译好得K2P_nano，就没有这两个选项。请教下修改哪几个文件呢？
