### ISSUE TITLE
DNSmasq: Add feature to filter IPv6 DNS record

### ISSUE THREAD

**Issue by kantkong** [hanwckf/rt-n56u#643]
For service DNSmasq:
          Please add option "filter-aaaa" to mask all AAAA record to clients, since much IPv6 DNS of websites are fail or slow.

    Detail of the patch may be refer to Branch of chongshengB, thanks.

**Comment by luoluodaduan** [comment]
这个版本 本身有 貌似 加了 filter-aaaa min ttl 可以直接用
