### ISSUE TITLE
各位大神求解怎么增加/etc/storage大小

### ISSUE THREAD

**Issue by lalasou** [hanwckf/rt-n56u#651]
自编译的k2p-nano固件 因为需要脚本跑ddns    hanwckf默认没有加入CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE
所以只能自己编译了
现在又跑了一个smartdns在/etc/storage
保存发现提示空间不够
想调整storage不知道在哪调整求大神带飞

固件其他功能都不需要
只在k2p-nano基础上
打开了
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE
能禁用的都禁用了
sftp留着呢😂

求大神指点￼
k2p nano基础上storage能增加到多少

**Comment by lededev** [comment]
需要改内核配置文件和mtd脚本，第一个填10进制的大小，第二个可以填16进制用0x开头，也可以填10进制。

trunk/user/scripts/mtd_storage.sh
mtd_part_size=

configs/boards/K2P/kernel-3.4.x-5.0.config
CONFIG_MTD_STORE_PART_SIZ=

**Comment by lalasou** [comment]
> 需要改内核配置文件和mtd脚本，第一个填10进制的大小，第二个可以填16进制用0x开头，也可以填10进制。
> 
> 
> 
> trunk/user/scripts/mtd_storage.sh
> 
> mtd_part_size=
> 
> 
> 
> configs/boards/K2P/kernel-3.4.x-5.0.config
> 
> CONFIG_MTD_STORE_PART_SIZ=

谢谢大佬，这个 k2p nano 可以设置多大空间啊

**Comment by lededev** [comment]
这个取决于你的闪存大小和固件编译选项。每次编译完成后会给出固件占用空间的报表，你可以按那个来计算决定你的storage的大小。

**Comment by lededev** [comment]
另外，smartdns已经进user了，配置时编译进固件即可，没必要再用storage来安装运行。

**Comment by lalasou** [comment]
> 另外，smartdns已经进user了，配置时编译进固件即可，没必要再用storage来安装运行。

好的  谢谢 
小白正在学  懂得少
