### ISSUE TITLE
Maximum number of concurrent DNS queries reached (max: 150)

### ISSUE THREAD

**Issue by cloudlose** [hanwckf/rt-n56u#66]
路由下面挂的玩客云这类的设备，用一段时间就会有这个错误提示，然后路由就会掉线死机，搜了一圈也没有找到怎么增加dns的并发查询数，有没有什么办法可以改善？

**Comment by hanwckf** [comment]
在`LAN -> DHCP服务器 ->自定义配置文件 "dnsmasq.conf"`中添加`dns-forward-max=1000`即可

**Comment by hanwckf** [comment]
死机可能是因为你的连接数超过了默认的最大连接数，在`防火墙 -> Netfilter`那边调大一点

**Comment by cloudlose** [comment]
感谢、之前连接数就设到最大了，目前没问题了，谢谢。
