### ISSUE TITLE
you're the bomb dude (5.0.5.1 doggie!)

### ISSUE THREAD

**Issue by i3roly** [hanwckf/rt-n56u#668]
@hanwckf, nice job as usual.

but why did you revert new ramcodes? compatibility with all devices?

possibly safe for DIR-882, DIR-{17,19,24}60+DIR-2640+DIR-30{40,60}?

**Comment by minax007** [comment]
If I were @hanwckf I would feel offended when reading the title. 
I would propose you to change it. 
Not in every culture addressing a person like this is tolerated. 
Even if it wasn't meant bad of yours.

**Comment by i3roly** [comment]
hello my chinese compadre! when i get some time later today, i will.

From: minax007
Sent: Saturday, 12 June 2021 12:20 AM
To: hanwckf/rt-n56u
Reply To: hanwckf/rt-n56u
Cc: gagan sidhu; Author
Subject: Re: [hanwckf/rt-n56u] you're the fucking bomb dude (5.0.5.1 doggie!) (#668)


If I were @hanwckf<https://github.com/hanwckf> I would feel offended when reading the title.
I would propose you to change it.
Not in every culture addressing a person like this is tolerated.
Even if it wasn't meant bad of yours.

**Comment by i3roly** [comment]
hahahhaha three thumbs down @minax007, you guys need to relax.

oh the charm of the chinese silence ;)
