### ISSUE TITLE
AP模式下访客网络失效

### ISSUE THREAD

**Issue by yaott2020-666** [hanwckf/rt-n56u#698]
如题，在AP模式下，访客网络与主网络直接互通，不能隔离。希望可以把访客网络单独设定一个br1 独立分配ip，并使用iptables隔离网络。由于padavan不像openwrt自由度高，因此这种操作有点繁杂。希望大佬可以修复这个功能，谢谢

**Comment by jinglei207** [comment]
分配IP是 路由器的工作，你自己都说了是做AP。

**Comment by yaott2020-666** [comment]
那在ap模式下，访客网络又意义何在呢

**Comment by jinglei207** [comment]
> 
> 
> 那在ap模式下，访客网络又意义何在呢

可以设置两个接入点啊！

**Comment by yaott2020-666** [comment]
两个接入点也要相互隔离啊

网上找到一篇和我的需求一样的，就是不知道命令可不可以用

https://koolshare.cn/thread-165614-1-1.html

**Comment by jinglei207** [comment]
> 两个接入点也要相互隔离啊
> 
> 网上找到一篇和我的需求一样的，就是不知道命令可不可以用
> 
> https://koolshare.cn/thread-165614-1-1.html

要弄肯定是可以弄的，但是要你自己用命令行设置。因为这需要配合上级路由器的设置，所以你要的功能这是不可能自带的。
关了吧。

**Comment by yaott2020-666** [comment]
已经实现了，贴个脚本:


guestwifi.sh
#########
#!/bin/sh
sleep 30
### Start ###
logger -t "【访客网络-AP模式】" "开始脚本!!"
# 将访客wlan从主网络中移除
logger -t "【访客网络-AP模式】" "将访客wlan从主网络中移除"
brctl delif br0 ra1
logger -t "【访客网络-AP模式】" "Done!!"
# 添加访客网络桥接接口
logger -t "【访客网络-AP模式】" "添加访客网络桥接接口"
brctl addbr br1
logger -t "【访客网络-AP模式】" "Done!!"
# 将访客wlan接口接入桥接接口
logger -t "【访客网络-AP模式】" "将访客wlan接口接入桥接接口"
brctl addif br1 ra1
logger -t "【访客网络-AP模式】" "Done!!"
# 配置桥接接口IPv4
logger -t "【访客网络-AP模式】" "配置桥接接口IPv4"
ifconfig br1 192.168.99.1 netmask 255.255.255.0 up
logger -t "【访客网络-AP模式】" "Done!!"
# 配置&启动dnsmasq
logger -t "【访客网络-AP模式】" "启动dnsmasq"
kill $(ps | grep dnsmasq | grep -v grep | awk '{print $1}')
dnsmasq --conf-file=/etc/storage/guest_network/dnsmasq.conf
logger -t "【访客网络-AP模式】" "Done!!"
logger -t "【访客网络-AP模式】" "配置防火墙隔离访客网络"
# 禁止访客网络主机访问AP
iptables -I INPUT -i br1 -j DROP
# 禁止访客网络主机互相访问
iptables -I INPUT -s 192.168.99.0/24 -d 192.168.99.0/24 -j DROP
# 禁止访客网络与主网络互通
iptables -I FORWARD -i br0 -o br1 -m state --state NEW -j DROP
# 禁止访问内网网段
iptables -I FORWARD -i br1 -d 192.168.1.0/24 -j DROP
# 允许访问DNS DHCP
iptables -I INPUT -i br1 -p udp -m multiport --dport 53,67:68 -j ACCEPT
logger -t "【访客网络-AP模式】" "Done!!"
logger -t "【访客网络-AP模式】" "配置NAT转发"
# NAT转发
iptables -t nat -A POSTROUTING -s 192.168.99.0/24 -j SNAT --to-source 192.168.2.2
logger -t "【访客网络-AP模式】" "Done!!"
# 开启内核转发功能
logger -t "【访客网络-AP模式】" "开启内核转发功能"
echo 1 > /proc/sys/net/ipv4/ip_forward
logger -t "【访客网络-AP模式】" "Done!!"
logger -t "【访客网络-AP模式】" "启动完成"
exit 0
#########

dnsmasq.conf
#########
user=nobody
port=53
no-dhcp-interface=br0
interface=br1
except-interface=br0
listen-address=192.168.99.1,127.0.0.1
cache-size=150
no-hosts
no-resolv
resolv-file=/etc/storage/guest_network/dns.conf
dhcp-range=192.168.99.10,192.168.99.50,255.255.255.0,12h
dhcp-option=3,192.168.99.1
dhcp-option=6,192.168.99.1,223.5.5.5
dhcp-leasefile=/tmp/dnsmasq.guest.leases
#########

dns.conf
#######
nameserver 192.168.1.1
nameserver 223.5.5.5
nameserver 119.29.29.29
#######

把文件放在/etc/storage/guest_network下,设置开机启动脚本就ok了
