### ISSUE TITLE
Mac电脑访问padavan后台非常慢

### ISSUE THREAD

**Issue by misakaok** [hanwckf/rt-n56u#700]
不知道作者能不能解决一下

**Comment by jinglei207** [comment]
换电脑。

**Comment by TurBoTse** [comment]
我还以为只有我的是这样。。。

**Comment by shengt25** [comment]
我还以为是路由器/固件出问题了，原来是这个问题吗

**Comment by AlexT1259** [comment]
#654 duplicated issue

**Comment by Yonsm** [comment]
用 nginx 反向代理可绕过此问题，相关 PR：https://github.com/hanwckf/rt-n56u/pull/755

**Comment by Yonsm** [comment]
竟然解决了：
启动前脚本加一行：

echo 0        > /proc/sys/net/ipv4/tcp_tw_recycle

**Comment by misakaok** [comment]
刷padavan 4.4内核的固件就好了
