### ISSUE TITLE
请求适配motorola mr2600，仅在dir882基础上修改一下天线增益即可！

### ISSUE THREAD

**Issue by cl0wnyzxu** [hanwckf/rt-n56u#74]
请求适配motorola mr2600，仅在dir882基础上修改一下天线增益即可！
这款路由和mr2600都是用的同一款公版模块，近日刷入dir882的padavan固件后发现天线增益只有20db，并不是原来mr2600的30db增益，最近在学习编译，但是没有找到可以修改天线增益的地方，希望大神可以在dir882的基础上修改一下，感激不尽！

**Comment by Jackson2002** [comment]
我也是请求适配，老哥搞定没，能不能留个联系方式
