### ISSUE TITLE
新编译的一个固件连接不上WAN/LAN

### ISSUE THREAD

**Issue by mars-byte** [hanwckf/rt-n56u#76]
首先感谢开源。

我自己试着编译的一个固件给这个路由https://openwrt.org/toh/hwdata/mtc/mtc_wr1201

2.4和5GWIFI都工作，USB也工作。可是lan和wan都连不上。lan得不到IP，wan也得不到IP。

看网络信息里，可以看到
WAN
Port Link			: 1000 Mbps, Full Duplex, FC TX/RX
LAN1
Port Link			: 100 Mbps, Full Duplex, FC TX/RX
应该说物理连接没有问题

**Comment by hanwckf** [comment]
ifconfig检查一下mac地址是不是全0

**Comment by mars-byte** [comment]
很奇怪 eth2 和rai2的mac是一样的

/home/root # ifconfig
br0       Link encap:Ethernet  HWaddr 00:16:FB:B6:E3:40
          inet addr:192.168.2.1  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:44970 errors:0 dropped:0 overruns:0 frame:0
          TX packets:45654 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:6370354 (6.0 MiB)  TX bytes:23597909 (22.5 MiB)

eth2      Link encap:Ethernet  HWaddr 00:16:FB:B6:E3:40
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7321 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:1647401 (1.5 MiB)
          Interrupt:11

eth3      Link encap:Ethernet  HWaddr 00:16:FB:B6:E3:43
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11352 errors:0 dropped:0 overruns:0 frame:0
          TX packets:804 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3950475 (3.7 MiB)  TX bytes:278184 (271.6 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:930 (930.0 B)  TX bytes:930 (930.0 B)

ra0       Link encap:Ethernet  HWaddr 00:16:FB:B6:D3:40
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:800 errors:0 dropped:0 overruns:0 frame:0
          TX packets:131 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:75821 (74.0 KiB)  TX bytes:12660 (12.3 KiB)
          Interrupt:32

rai0      Link encap:Ethernet  HWaddr 00:16:FB:B6:E3:40
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:45462 errors:0 dropped:0 overruns:0 frame:0
          TX packets:49341 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8235193 (7.8 MiB)  TX bytes:22565358 (21.5 MiB)
          Interrupt:12

**Comment by mars-byte** [comment]
搞定了，W/L 顺序搞错了。改成LLLW就行了。

除了TF卡还没试，其他都工作。回头找张TF卡试试。

如果感兴趣的话，我可以create一个pull request

**Comment by mars-byte** [comment]
TF卡可以识别，但是没有挂载。怎么自动挂载？
