### ISSUE TITLE
通过本地编译和云编译，插件都无法加入。发生了什么呢？

### ISSUE THREAD

**Issue by lhuanyun** [hanwckf/rt-n56u#760]
以下是我的R6900v2固件的配置文件，最后几行。
[rt-n56u](https://github.com/lhuanyun/rt-n56u)/[trunk](https://github.com/lhuanyun/rt-n56u/tree/master/trunk)/[configs](https://github.com/lhuanyun/rt-n56u/tree/master/trunk/configs)/[templates](https://github.com/lhuanyun/rt-n56u/tree/master/trunk/configs/templates)/NETGEAR-BZV.config
----------------
CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n

CONFIG_FIRMWARE_INCLUDE_FRPC=n

CONFIG_FIRMWARE_INCLUDE_FRPS=y

CONFIG_FIRMWARE_INCLUDE_TUNSAFE=y

CONFIG_FIRMWARE_INCLUDE_WIREGUARD=y

CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y

CONFIG_FIRMWARE_INCLUDE_SSSERVER=n

CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y

CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y
-------------------------------------------------------
试了太多次了，一直这样。
谢谢各位，帮我找找问题。编译出来，就是没有SMARTDNS和WIREGUARD,FRPS。

**Comment by kkjoy** [comment]
建议你看一下 https://github.com/felix-fly/v2ray-padavan-doh

**Comment by lhuanyun** [comment]
> 建议你看一下 https://github.com/felix-fly/v2ray-padavan-doh

感谢，🙏

**Comment by dust2k** [comment]
应该是改 build_firmware_modify里的选项吧，我记得.config里的选项会被overwrite掉。。

**Comment by wenpo1975** [comment]
我也遇到了，正在找问题
