### ISSUE TITLE
R2100的WiFi在ipv6测速时下行速度异常

### ISSUE THREAD

**Issue by nantayo** [hanwckf/rt-n56u#763]
使用最新源码编译出R2100固件，版本为【3.4.3.9-099_ff4ff48】。在华工校园网内使用，已经参照[说明](https://github.com/hanwckf/scut_padavan_guide/blob/master/guide.md#ipv6)配置好，并可以正常访问ipv6网站。
![2](https://user-images.githubusercontent.com/77558823/174715451-54e1e102-ba09-4316-875f-72610c03dea6.png)
***
其中，有线网络一切正常，可通过[测试](https://www.test-ipv6.com/index.html.zh_CN)，且ipv6测速结果正常：
![1](https://user-images.githubusercontent.com/77558823/174715572-c05eb42f-3cf3-467f-b9ac-c8634711822c.png)
***
然而，无线网络存在下行几乎无速度的问题，也可通过[测试](https://www.test-ipv6.com/index.html.zh_CN)。但ipv6测速时，无论使用5G WiFi或是2.4G WiFi，下行都只有1兆左右徘徊，同时上行可达几百兆，为正常速度：
![3](https://user-images.githubusercontent.com/77558823/174716029-91c23830-b063-49b5-a3db-89c6fa694f57.png)
***
对5G WiFi追加测试，获得了如下结果：  

使用iperf3测速：下行可稳定达到900兆左右，是正常的160Mhz WiFi水平。  

使用其他ipv4网站测速：下行测速稳定为20兆左右，是正常的校园网限速水平。  

观看哔哩哔哩高码率视频，如4K HDR视频等：观察到拖动进度条时，下行最高可超过10MB/s，且能够持续数秒。这远超校园网ipv4限速的20兆，与PC端有线连接观察到的下行速度差不多。推断B站视频能够通过ipv6网络分发，且此时WiFi的ipv6速度正常。  

观看微信公众号文章、微信群聊表情包、哔哩哔哩专栏图片：观察到存在图片加载缓慢，偶尔无法加载需要手动点击的问题。推断这些内容也是通过ipv6网络分发，且此时WiFi的ipv6速度不正常，与测速一样都只有1兆左右。
***
对不同固件追加测试，获得了如下结果：  

使用Lean的[OpenWrt](https://github.com/coolsnowwolf/lede)编译出内核为5.4.199的固件，可通过[测试](https://www.test-ipv6.com/index.html.zh_CN)，ipv6测速结果无论有线还是无线，都只有1兆左右，而且OpenWrt的WiFi非常难连接上，经常提示网络拒绝接入。
当然，OpenWrt使用ipv6的设置方法与Padavan非常不同，这可能是我自己设置错误导致的。  

使用PadavanOnly的[Padavan](https://github.com/padavanonly/rt-n56u)编译出内核为3.4.3.9-099的固件，与直接使用本仓库编译出的固件结果一样，都是有线正常无线异常。
***
由以上测试，我个人猜想，ipv6的无线下行速度异常，是否可能是本仓库现在使用的MT7615芯片的驱动程序存在一定兼容性问题？
如果是，应该回滚到哪个commit重新编译尝试？如果不是，还有可能是哪里存在问题，应该从何入手进行排查？

**Comment by nantayo** [comment]
补充一下:
除了这台小米的AC2100以外，我还有一台斐讯K2（PSG1218），同样用本仓库的最新源码编译的固件，使用几乎相同的设置，其ipv6在5G WiFi的下行速度是正常的，可以跑到将近百兆。  

在固件中我尝试开关hwnat，sfe加速，ipv6加速这三处，任意组合都存在无线下行只有1兆的问题。

**Comment by nantayo** [comment]
换用4.4内核的源码编译的固件正常，完结。

**Comment by Ares-Liang** [comment]
> 换用4.4内核的源码编译的固件正常，完结。

请问如何更换到4.4内核的源码？谢谢
