### ISSUE TITLE
K2P: ApCli模式下无法显示上级AP的连接信息

### ISSUE THREAD

**Issue by hanwckf** [hanwckf/rt-n56u#8]

**Comment by bugme2** [comment]
> _No description provided._

![qq 20181115095415](https://user-images.githubusercontent.com/40169265/48524738-7b9a3700-e8bc-11e8-9594-7696b0e9ccbf.png)
好像没显示全

**Comment by ferhung-mtk** [comment]
我回退到了mt7615的4.4.1.2驱动，启用了wsc，目前来看没遇到这个问题
[https://github.com/ferhung-mtk/rt-n56u/commit/27f1e1ee95e0f6d0e9dae7922c75ee801982eb95](url)
