### ISSUE TITLE
如何把主页面那个“2.4Ghz 无线“从菜单里删除？

### ISSUE THREAD

**Issue by MayaGates** [hanwckf/rt-n56u#85]
本人是小白，想编译一个没有无线驱动的padavan，“5GHz 无线”这个菜单自动消失掉了，但是“2.4Ghz 无线“不能消失。看了源码，没看明白，如何把主页面那个“2.4Ghz 无线“从菜单里删除？请高手指正。

**Comment by Yonsm** [comment]
已pr，现在可以删除了
