### ISSUE TITLE
无线网（5G）的ipv6好像速度不行

### ISSUE THREAD

**Issue by BenjaminRace** [hanwckf/rt-n56u#95]
坐标大连理工，校园网千兆端口，用scut padavan下载6v，有线速度和电脑直连网线一样，可是用无线5g速度就只有2-3M，而且上传几乎等于下载

**Comment by hanwckf** [comment]
是用napt66么，这玩意好像有未知bug, 在前缀长度128的网络里面速率会变得奇怪

**Comment by BenjaminRace** [comment]
对,是napt66
怎么解决?把前缀换成64?但这个是校园网的锅吧

**Comment by hanwckf** [comment]
没有解决办法，换openwrt吧
